---
title: "AggregateCounts"
author: "Juan P Barraza"
date: "6/4/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(conflicted)
library(tidyverse)
library(plotrix)#for std error
library(dplyr)
library(cowplot)
filter <- dplyr::filter
library(EBImage) #for rtiff

```

```{r aggregate input}
#agregate input functions
ReadAggregateFile<-function(file, species, timepoint, condition, replicate,fileName, sampleCode){#make a dataframe of the aggregate size list and add experimental parameters
  print(file)
   datos <-read.csv(file, header = F)  
   colnames(datos)<-c('Size') 
   datos<-datos %>% filter(!Size<0.5) #first filter the size
   datos<-datos %>% mutate(Species = species)#add parameters
   datos<-datos %>% mutate(TimePoint = timepoint) 
   datos<-datos %>% mutate(Condition = condition)
   datos<-datos %>% mutate(Replicate = replicate)
   datos<-datos %>% mutate(SampleCode = sampleCode)
   datos<-datos %>% mutate(FileName = fileName)
   datos$Species<-as.factor(datos$Species)
   datos$Replicate<-as.factor(datos$Replicate)
   datos$Condition<-as.factor(datos$Condition)
   datos$TimePoint<-as.factor(datos$TimePoint)
   datos$FileName<-as.factor(datos$FileName)
   datos$SampleCode<-as.factor(datos$SampleCode)
   
   return(datos)
}
GetAggregates<-function(){#import all experiments at once
   folder<- paste0('/Volumes/raw_data/Confocal/Carolyn/2020/Chronic wounds/Aggregate lists')
   fileList<-list.files(path = folder, full.names = TRUE)
   growthDf<-data.frame()
   for (aggList in 1:length(fileList)){
     fileName<-str_split(basename(fileList[aggList]), "\\.")[[1]][1]#this selects the base file name and removes the ".csv"
     attrList<-str_split(fileName,"_")[[1]]
     sampleCode = paste0(attrList[1],"_",attrList[2],"_",attrList[3])
     growthDf<-rbind(growthDf,ReadAggregateFile(fileList[aggList],attrList[4],attrList[2],attrList[1],attrList[3], fileName, sampleCode))}
   return(growthDf)
}

#run functions
aggregateList<-GetAggregates()#this reads the data from Matlab

#remove bad samples and irrelevant conditions
##first remove irrelevant conditions
removable <- bind_rows(aggregateList %>% filter(Species == "Pa" & Condition == "mono"), #Pa in Sa mono culture
                       aggregateList%>% filter(Species == "Sa" & Condition == "pawt"),#Sa in all Pa mono cultures
                       aggregateList%>% filter(Species == "Sa" & Condition == "papqsL"),
                       aggregateList%>% filter(Species == "Sa" & Condition == "paphz"))
aggregateList <- anti_join(aggregateList, removable)
##then, bad samples
aggregateList<-aggregateList %>% filter(!SampleCode == "mono_d1_03")
aggregateList<-aggregateList %>% filter(!SampleCode == "phz_d4_14")
aggregateList<-aggregateList %>% filter(!SampleCode == "pqsL_d4_02")
aggregateList<-aggregateList %>% filter(!SampleCode == "pqsL_d4_04")
aggregateList<-aggregateList %>% filter(!SampleCode == "pqsL_d4_10")
aggregateList<-aggregateList %>% filter(!SampleCode == "wt_d4_07")
aggregateList<-aggregateList %>% filter(!SampleCode == "papqsL_d4_02")
aggregateList<-aggregateList %>% filter(!SampleCode == "pawt_d4_05")
aggregateList<-aggregateList %>% filter(!SampleCode == "phz_d4_06")

#add proper labels for plots
aggregateList$Species <- factor(aggregateList$Species, levels = c("Pa", "Sa"),labels = c('P. aeruginosa','S. aureus'))
aggregateList$Condition <- factor(aggregateList$Condition, levels = c("mono", "pawt","papqsL", "paphz", "wt", "pqsL", "phz"),
                                  labels = c('Sa mono', 'wt mono','pqsL mono','phz mono','wt co', 'pqsL co', 'phz co'))
aggregateList$TimePoint <- factor(aggregateList$TimePoint, levels = c("d1", "d4"),labels = c('Day 1','Day 4'))

aggregateList<-aggregateList %>% mutate(Culture = recode(Condition, 'Sa mono' = "mono", 'wt mono' = "mono",'pqsL mono'= "mono",'phz mono'= "mono",'wt co'= "co", 'pqsL co'= "co", 'phz co'= "co"))
aggregateList<-aggregateList%>% mutate(Strain = recode(Condition, 'Sa mono' = "Sa", 'wt mono' = "wt",'pqsL mono'= "pqsL",'phz mono'= "phz",'wt co'= "wt", 'pqsL co'= "pqsL", 'phz co'= "phz"))
aggregateList<-aggregateList%>% mutate(SaStrain = recode(Condition, 'Sa mono' = "Sa mono", 'wt mono' = "wt",'pqsL mono'= "pqsL",'phz mono'= "phz",'wt co'= "co-wt", 'pqsL co'= "co-pqsL", 'phz co'= "co-phz"))

#Adding the metadata
metaData <-read.csv('/Volumes/raw_data/Confocal/Carolyn/2020/Chronic wounds/images metadata.csv', header = TRUE)
metaData<-metaData %>% select(SampleCode, mouse, Position, size, Region, Zdim, xyDim,xySize)
aggregateList<-metaData %>%  merge(aggregateList)
aggregateList$Region<-as.factor(aggregateList$Region)

#---This chunk creates 'aggregateList' data frame, which contains all the aggregates per sample and it is on the correct format
```

```{r aggregate wrangling}
#Statistics from all aggregates
#Get aggregate summary per sample
aggregateListSummaryReplicate<-aggregateList%>% group_by(SampleCode,Species,SaStrain,Strain,Culture,TimePoint,Condition,Replicate,Region) %>% 
  summarise(Aggs = n(), Biomass = sum(Size), MeanAggSize = mean(Size), SEAggSize = std.error(Size), MaxSize = max(Size), MinSize = min(Size)) %>%
  ungroup() %>% mutate(RatioMaxTotal = MaxSize/Biomass) 

#Get aggregate Summary per condition
aggregateListSummaryCondNoRegion<-aggregateListSummaryReplicate %>% group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition) %>% 
  summarise(MeanAggs= mean(Aggs), MeanBiomassLog = mean(log10(Biomass)), SEBiomassLog = std.error((log10(Biomass))), MeanMeanAggSize = mean(MeanAggSize), SEMeanAggSize = std.error(MeanAggSize))

#Get aggregate Summary per condition and region
aggregateListSummaryCondition<-aggregateListSummaryReplicate %>% group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition,Region) %>% summarise(MeanAggs= mean(Aggs), MeanBiomassLog = mean(log10(Biomass)), SEBiomassLog = std.error((log10(Biomass))), MeanMeanAggSize = mean(MeanAggSize), SEMeanAggSize = std.error(MeanAggSize))

#T-tests for biomass and Aggs
TtestTable<-name <- function(dataPoint) {data <-data.frame(dataPoint$data.name, dataPoint$p.value)}
##WT co vs mono comparisons
###Biomass and Aggs of Pa mono vs co
PaWtmono<-aggregateListSummaryReplicate %>% filter(Species == "P. aeruginosa" & TimePoint == "Day 4", Strain == "wt", Culture == "mono")
PaWtco<-aggregateListSummaryReplicate %>% filter(Species == "P. aeruginosa" & TimePoint == "Day 4", Strain == "wt", Culture == "co")
PaWtonovsCoBiomassTtest<-t.test(x = PaWtmono$biomass, y = PaWtco$biomass, paired = F)
PaWtonovsCoAggsTtest<-t.test(x = PaWtmono$Aggs, y = PaWtco$Aggs, paired = F)
###Biomass and Aggs of Sa mono vs co
SaWtmono<-aggregateListSummaryReplicate %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "Sa", Culture == "mono")
SaWtco<-aggregateListSummaryReplicate %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "wt", Culture == "co")
SaWtonovsCoBiomassTtest<-t.test(x = SaWtmono$biomass, y = SaWtco$biomass, paired = F)
SaWtonovsCoAggsTtest<-t.test(x = SaWtmono$Aggs, y = SaWtco$Aggs, paired = F)
###Biomass and Aggs of Pa core vs edge co-culture
PaWtCoEdge<-aggregateListSummaryReplicate %>% filter(Species == "P. aeruginosa"&TimePoint =="Day 4",Strain == "wt",Culture == "co",Region == "edge")
PaWtcoCore<-aggregateListSummaryReplicate %>% filter(Species == "P. aeruginosa"&TimePoint =="Day 4",Strain == "wt",Culture == "co",Region == "core")
PaWtCoEdgevsCoreBiomassTtest<-t.test(x = PaWtCoEdge$biomass, y = PaWtcoCore$biomass, paired = F)
PaWtCoEdgevsCoreAggsTtest<-t.test(x = PaWtCoEdge$Aggs, y = PaWtcoCore$Aggs, paired = F)
###Biomass and Aggs of Sa core vs edge co-culture
SaWtCoEdge<-aggregateListSummaryReplicate %>% filter(Species == "S. aureus"&TimePoint =="Day 4",Strain == "wt",Culture == "co",Region == "edge")
SaWtcoCore<-aggregateListSummaryReplicate %>% filter(Species == "S. aureus"&TimePoint =="Day 4",Strain == "wt",Culture == "co",Region == "core")
SaWtCoEdgevsCoreBiomassTtest<-t.test(x = SaWtCoEdge$biomass, y = SaWtcoCore$biomass, paired = F)
SaWtCoEdgevsCoreAggsTtest<-t.test(x = SaWtCoEdge$Aggs, y = SaWtcoCore$Aggs, paired = F)

tTestFigs1ABData<-list(PaWtonovsCoBiomassTtest,PaWtonovsCoAggsTtest,PaWtCoEdgevsCoreBiomassTtest,PaWtCoEdgevsCoreAggsTtest,
                       SaWtonovsCoBiomassTtest,SaWtonovsCoAggsTtest,SaWtCoEdgevsCoreBiomassTtest,SaWtCoEdgevsCoreAggsTtest)
tTestFigs1ABTable<-bind_rows(map(tTestFigs1ABData, TtestTable))
##co wt vs mutants
###Biomass and Aggs of Pa wt vs mutants
PaBiomassAov <- aov(biomass ~ Strain, data = aggregateListSummaryReplicate %>% 
                           filter(Species == "P. aeruginosa" & TimePoint == "Day 4", Culture == "co"))
PaAggsAov <- aov(Aggs ~ Strain, data = aggregateListSummaryReplicate %>% 
                           filter(Species == "P. aeruginosa" & TimePoint == "Day 4", Culture == "co"))
###Biomass and Aggs of Sa wt vs mutants
SaBiomassAov <- aov(biomass ~ Strain, data = aggregateListSummaryReplicate %>% 
                           filter(Species == "S. aureus" & TimePoint == "Day 4", Culture == "co"))
SaAggsAov <- aov(Aggs ~ Strain, data = aggregateListSummaryReplicate %>% 
                           filter(Species == "S. aureus" & TimePoint == "Day 4", Culture == "co"))
summary(PaAggsAov)
TukeyHSD(PaAggsAov)#wt~pqsL p = 0.06, wt~phz p = 0.003
summary(SaAggsAov)
TukeyHSD(SaAggsAov)#wt~pqsL p = 0.03
###Core vs edge within mutants
PaPqsLmassE<-aggregateListSummaryReplicate %>% filter(Species =="P. aeruginosa",TimePoint =="Day 4",Strain == "pqsL",Culture == "co",Region == "edge")
PaPqsLmassC<-aggregateListSummaryReplicate %>% filter(Species =="P. aeruginosa",TimePoint =="Day 4",Strain == "pqsL",Culture == "co",Region == "core")
PaPhzmassE<-aggregateListSummaryReplicate %>% filter(Species == "P. aeruginosa",TimePoint =="Day 4",Strain == "phz",Culture == "co",Region == "edge")
PaPhzmassC<-aggregateListSummaryReplicate %>% filter(Species == "P. aeruginosa",TimePoint =="Day 4",Strain == "phz",Culture == "co",Region == "core")

SaPqsLmassE<-aggregateListSummaryReplicate %>% filter(Species =="S. aureus",TimePoint =="Day 4",Strain == "pqsL",Culture == "co",Region == "edge")
SaPqsLmassC<-aggregateListSummaryReplicate %>% filter(Species =="S. aureus",TimePoint =="Day 4",Strain == "pqsL",Culture == "co",Region == "core")
SaPhzmassE<-aggregateListSummaryReplicate %>% filter(Species == "S. aureus",TimePoint =="Day 4",Strain == "phz",Culture == "co",Region == "edge")
SaPhzmassC<-aggregateListSummaryReplicate %>% filter(Species == "S. aureus",TimePoint =="Day 4",Strain == "phz",Culture == "co",Region == "core")

PaPqsLCoEdgevsCoreBiomassTtest<-t.test(x = PaPqsLmassE$biomass, y = PaPqsLmassC$biomass, paired = F)
PaPqsLCoEdgevsCoreAggsTtest<-t.test(x = PaPqsLmassE$Aggs, y = PaPqsLmassC$Aggs, paired = F)
PaPhzCoEdgevsCoreBiomassTtest<-t.test(x = PaPhzmassE$biomass, y = PaPhzmassC$biomass, paired = F)
PaPhzCoEdgevsCoreAggsTtest<-t.test(x = PaPhzmassE$Aggs, y = PaPhzmassC$Aggs, paired = F)

SaPqsLCoEdgevsCoreBiomassTtest<-t.test(x = SaPqsLmassE$biomass, y = SaPqsLmassC$biomass, paired = F)
SaPqsLCoEdgevsCoreAggsTtest<-t.test(x = SaPqsLmassE$Aggs, y = SaPqsLmassC$Aggs, paired = F)
SaPhzCoEdgevsCoreBiomassTtest<-t.test(x = SaPhzmassE$biomass, y = SaPhzmassC$biomass, paired = F)
SaPhzCoEdgevsCoreAggsTtest<-t.test(x = SaPhzmassE$Aggs, y = SaPhzmassC$Aggs, paired = F)

tTestFigs2ABDataCvsE<-list(PaPqsLCoEdgevsCoreBiomassTtest,PaPqsLCoEdgevsCoreAggsTtest,PaPhzCoEdgevsCoreBiomassTtest,PaPhzCoEdgevsCoreAggsTtest,
                           SaPqsLCoEdgevsCoreBiomassTtest,SaPqsLCoEdgevsCoreAggsTtest,SaPhzCoEdgevsCoreBiomassTtest,SaPhzCoEdgevsCoreAggsTtest)
tTestFigs2ABTableCvsE<-bind_rows(map(tTestFigs1ABDataCvsE, TtestTable))


```

```{r biomass, aggregate number and mean size Plots}
#Plot agg summary per sample
#####
ggplot()+ 
  geom_jitter(data = aggregateListSummaryReplicate, aes(x = TimePoint, y= meanAggSize, color = Strain,shape = "MeanSize"),size = 3, height = 0, width = .3)+
  geom_jitter(data = aggregateListSummaryReplicate, aes(x = TimePoint, y= maxSize, color = Strain, shape = "MaxSize"),size = 3, height = 0, width = .3)+
  geom_jitter(data = aggregateListSummaryReplicate, aes(x = TimePoint, y= biomass, color = Strain, shape = "TotalBiomass"),size = 3, height = 0,width= .3)+
  scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  facet_grid(Species~Culture, scales = "free", space = "free") +
  ggtitle('Mean size and largest aggregate and total biomass per sample')+
  labs(x = "",y = bquote(paste("Volume (", mu*"m"^3*")")))+
  scale_shape_manual(name="Metric",values=c(MeanSize=1, MaxSize=2, TotalBiomass=17))+
  scale_color_brewer(palette = "Set1")+
  theme_cowplot()+
  panel_border() +
  theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
#####
#Plot only biomass per Sample
#####
PlotBiomasPerSample<-function(df){
ggplot()+ 
    #this is for multiple conditions
  #geom_point(data = df, aes(x = Strain, y= biomass, shape = Region, color = Culture),size = 3, position = position_dodge(width = .6))+
  geom_point(data = df, aes(x = Culture, y= biomass, color= Species, shape = Region),size = 3, 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75))+
    scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)), limits = c(1, 100000000))+
      #this is for multiple conditions  
    #facet_grid(Species~TimePoint, scales = "free", space = "free") +
    #this is for only one mutant
    facet_grid(.~TimePoint, scales = "free", space = "free") +
  ggtitle('Total biomass per sample')+
  labs(x = "",y = bquote(paste("Volume (", mu*"m"^3*")")))+
  scale_color_brewer(palette = "Set1")+
  scale_shape_manual(values=c(1, 2,0))+
  theme_cowplot()+
  panel_border() +
  theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}

#plotting all conditions
PlotBiomasPerSample(aggregateListSummaryReplicate)
#plotting only Sa and pa wt in mono and co-culture
PlotBiomasPerSample(aggregateListSummaryReplicate %>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"))
#####

#plot agg summary per condition#this shows both contition and replicate
#####
PlotBiomassPerCondition<-function(df, metric, error){
ggplot()+ 
  geom_pointrange(data = df, aes(x = Culture, y= .data[[metric]],
                                 ymax=.data[[metric]]+.data[[error]],ymin =.data[[metric]]-.data[[error]], color = Strain,shape = Region), 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75))+
  scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)), limits = c(10000,1000000000))+
  facet_grid(Species~TimePoint, scales = "free", space = "free") +
  ggtitle('Mean size per condition and region')+
  labs(x = "",y = bquote(paste("Volume (", mu*"m"^3*")")))+
  #scale_shape_manual(name="Metric",values=c(MeanSize=1, MaxSize=2, TotalBiomass=17))+
  scale_color_brewer(palette = "Set1")+
    theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facets
          strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))
}

PlotBiomassPerCondition(aggregateListSummaryCondition,"meanBiomass", "SEBiomass")
#####


#Plotting mean and all samples
PlotBiomasPerSampleAndConditionWT<-function(df1,df2, df3){
ggplot()+ 
    geom_point(data = df1 %>% filter(TimePoint=="Day 4"), aes(x = Culture, y= meanBiomassLog,shape = Region), 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75), size = 4)+
  geom_point(data = df2%>% filter(TimePoint=="Day 4"), aes(x = Culture, y= log10(biomass), shape = Region),size = 1, 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75))+
    geom_point(data = df3 %>% filter(TimePoint=="Day 4"), aes(x = Culture, y= meanBiomassLog),shape = 3,size = 4)+
    #scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)), limits = c(1, 100000000))+
      facet_grid(.~Species, scales = "free", space = "free") +
  ggtitle('Biomass per sample')+
  labs(x = "",y = bquote(paste("log10 Volume (", mu*"m"^3*")")))+
  scale_color_brewer(palette = "Set1")+
  scale_shape_manual(values=c(16, 1))+
  ylim(0,8)+
    theme_cowplot()+
  panel_border() +
  theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}

#WT only
PlotBiomasPerSampleAndConditionWT(aggregateListSummaryCondition%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"),
                                aggregateListSummaryReplicate %>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"), 
                                aggregateListSummaryCondNoRegion%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"))

PlotBiomasPerSampleAndCondition<-function(df1,df2, df3,xAxis){
ggplot()+ 
    geom_point(data = df1 %>% filter(TimePoint=="Day 4") , aes(x = .data[[xAxis]], y= meanBiomassLog,shape = Region), 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75), size = 4)+
  geom_point(data = df2%>% filter(TimePoint=="Day 4") , aes(x = .data[[xAxis]], y= log10(biomass), shape = Region),size = 1, 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75))+ 
  geom_point(data = df3 %>% filter(TimePoint=="Day 4"), aes(x = .data[[xAxis]], y= meanBiomassLog), shape = 3, size = 4)+
    #scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)), limits = c(1, 100000000))+
      facet_grid(.~Species, scales = "free", space = "free") +
  ggtitle('Total Biomass')+
  labs(x = "",y = bquote(paste("Volume (log10", mu*"m"^3*")")))+
  scale_color_brewer(palette = "Set1")+
  scale_shape_manual(values=c(16, 1))+
  ylim(0,8)+
    theme_cowplot()+
  panel_border() +
  theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}

PlotMeanAggsPerSampleAndConditionWT<-function(df1,df2, df3){
ggplot()+ 
    geom_point(data = df1 %>% filter(TimePoint=="Day 4"), aes(x = Culture, y= meanAggs,shape = Region), 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75), size = 4)+
  geom_point(data = df2%>% filter(TimePoint=="Day 4"), aes(x = Culture, y= Aggs, shape = Region),size = 1, 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75))+
    geom_point(data = df3 %>% filter(TimePoint=="Day 4"), aes(x = Culture, y= meanAggs),shape = 3,size = 4)+
    scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)), limits = c(10, 100000))+
      facet_grid(.~Species, scales = "free", space = "free") +
  ggtitle('Number of groups of bacteria')+
  labs(x = "",y = "")+
  scale_color_brewer(palette = "Set1")+
  scale_shape_manual(values=c(16, 1))+
  #ylim(0,8)+
    theme_cowplot()+
  panel_border() +
  theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}

PlotMeanAggsPerSampleAndCondition<-function(df1,df2, df3, xAxis){
ggplot()+ 
    geom_point(data = df1 %>% filter(TimePoint=="Day 4") , aes(x = .data[[xAxis]], y= meanAggs,shape = Region), 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75), size = 4)+
  geom_point(data = df2%>% filter(TimePoint=="Day 4"), aes(x = .data[[xAxis]], y= Aggs, shape = Region),size = 1, 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75))+
    geom_point(data = df3 %>% filter(TimePoint=="Day 4"), aes(x = .data[[xAxis]], y= meanAggs),shape = 3,size = 4)+
    scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)), limits = c(1, 100000))+
      facet_grid(.~Species, scales = "free", space = "free") +
  ggtitle('Number of groups of bacteria')+
  labs(x = "",y = "")+
  scale_color_brewer(palette = "Set1")+
  scale_shape_manual(values=c(16, 1))+
  #ylim(0,8)+
    theme_cowplot()+
  panel_border() +
  theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}

PlotMeanAggsPerSampleAndConditionPa<-function(df1,df2, df3,species){
ggplot()+ 
    geom_point(data = df1 %>% filter(TimePoint=="Day 4") %>% filter(Species == species), aes(x = Strain, y= meanAggs,shape = Region, color= Region), 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75),
             fill = "black", size = 4)+
  geom_point(data = df2%>% filter(TimePoint=="Day 4")%>% filter(Species == species), aes(x = Strain, y= Aggs, shape = Region, color = Region),size = 1, fill = "black", 
             position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75))+
    geom_point(data = df3 %>% filter(TimePoint=="Day 4")%>% filter(Species == species), aes(x = Strain, y= meanAggs),shape = 3,size = 4)+
    scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)), limits = c(10, 100000))+
      facet_grid(.~Culture, scales = "free", space = "free") +
  ggtitle('Number of groups of bacteria')+
  labs(x = "",y = "")+
  #scale_color_brewer(palette = "Set1")+
  scale_color_manual(values = c("white", "black"))+
  scale_shape_manual(values=c(21, 1))+
  #ylim(0,8)+
    theme_cowplot()+
  panel_border() +
  theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}

```

```{r figures 1A,1B and 2A, 2B}
#Biomass wt
PlotBiomasPerSampleAndConditionWT(aggregateListSummaryCondition%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"),
                                aggregateListSummaryReplicate %>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"), 
                                aggregateListSummaryCondNoRegion%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"))
#Biomass Sa and mutants
PlotBiomasPerSampleAndCondition(aggregateListSummaryCondition%>% filter(Culture=="co"),
                                aggregateListSummaryReplicate%>% filter(Culture=="co"),
                                aggregateListSummaryCondNoRegion%>% filter(Culture=="co"),"SaStrain")

#Number of aggregates wt
PlotMeanAggsPerSampleAndConditionWT(aggregateListSummaryCondition%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"),
                                aggregateListSummaryReplicate %>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"), 
                                aggregateListSummaryCondNoRegion%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"))

#Number of aggregates Sa and mutants
PlotMeanAggsPerSampleAndCondition(aggregateListSummaryCondition%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"),
                                aggregateListSummaryReplicate%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"), 
                                aggregateListSummaryCondNoRegion%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "Pa wt mono"), "Culture")

PlotMeanAggsPerSampleAndCondition(aggregateListSummaryCondition %>% filter(Culture=="co"),
                                aggregateListSummaryReplicate%>% filter(Culture=="co"), 
                                aggregateListSummaryCondNoRegion%>% filter(Culture=="co"),"SaStrain")
```

```{r Aggregate size bins}
#histogram<- hist(aggregateList$Size, breaks = c(0, 5, 10, 100, 1000, 10^9))#this is a simple way to do a histogram

#this pipe essentially gets to the product of what fancy histograms do but more efficiently
#First including all sizes

#There are two ways to normalize the Bin Frequncy and Bin Biomass, per condition and per sample, so I'll do both
#First per replicate:
#####
HistReplicate<-aggregateList %>% mutate(LogBin = case_when(Size <= 5 ~ "(.5, 5]",
                        Size<= 10 ~ "(5, 10]",
                        Size<= 100    ~ "(10, 100]",
                        Size<= 1000   ~ "(100, 1000]",
                        Size> 1000  ~ paste0("(1000, ",bquote("\U221E"), ")"))) %>% 
  group_by(SampleCode,Species)%>% 
  mutate(TotalBiomass = sum(Size), TotalFrequency = n()) %>% ungroup() %>% 
  group_by(SampleCode,Species,LogBin)%>%
  mutate(BinBiomass = sum(Size), BinFrequency = n()) %>% ungroup() %>%
  mutate(NormalizedFrequency = BinFrequency/TotalFrequency*100, NormalizedBiomass = BinBiomass/TotalBiomass*100)

HistReplicate$LogBin <- factor(HistReplicate$LogBin, levels = c("(.5, 5]", "(5, 10]","(10, 100]", "(100, 1000]", paste0("(1000, ",bquote("\U221E"), ")")),labels = c(levels = c("(.5, 5]", "(5, 10]","(10, 100]", "(100, 1000]", paste0("(1000, ",bquote("\U221E"), ")"))))

#This is weird, but I want to have the histogram above with all the data, and the one below with only the bins
HistReplicateSummary<-HistReplicate %>% 
  group_by(SampleCode,Species,SaStrain,Strain,Culture,TimePoint,Condition,Replicate,Region,LogBin,NormalizedFrequency,NormalizedBiomass) %>% summarize() %>%
  unique()%>%ungroup() %>%  group_by(SampleCode,Species,SaStrain,Strain,Culture,TimePoint,Condition,Replicate,Region) %>% 
  mutate(checkSumFreq =sum(NormalizedFrequency), checkSumBiomass = sum(NormalizedBiomass))
#####
#Now per condition. The difference is int the "group_by" part
#####
HistCondition<-aggregateList %>% mutate(LogBin = case_when(Size <= 5 ~ "(.5, 5]",
                        Size<= 10 ~ "(5, 10]",
                        Size<= 100    ~ "(10, 100]",
                        Size<= 1000   ~ "(100, 1000]",
                        Size> 1000  ~ paste0("(1000, ",bquote("\U221E"), ")"))) %>% 
  group_by(Species,Condition,TimePoint)%>% 
  mutate(TotalBiomass = sum(Size), TotalFrequency = n()) %>% ungroup() %>% 
  group_by(Species,Condition,TimePoint,LogBin)%>%
  mutate(BinBiomass = sum(Size), BinFrequency = n()) %>% ungroup() %>%
  mutate(NormalizedFrequency = BinFrequency/TotalFrequency*100, NormalizedBiomass = BinBiomass/TotalBiomass*100)
HistCondition$LogBin <- factor(HistCondition$LogBin, levels = c("(.5, 5]", "(5, 10]","(10, 100]", "(100, 1000]", paste0("(1000, ",bquote("\U221E"), ")")),labels = c(levels = c("(.5, 5]", "(5, 10]","(10, 100]", "(100, 1000]", paste0("(1000, ",bquote("\U221E"), ")"))))

#Summary data frame
HistConditionSummary<-HistCondition %>%
  group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition,LogBin,NormalizedFrequency,NormalizedBiomass) %>% 
  summarize() %>% unique()%>%ungroup() %>%
  group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition) %>% 
  mutate(checkSumFreq =sum(NormalizedFrequency), checkSumBiomass = sum(NormalizedBiomass))
#####
#Now per condition including region. The difference is int the "group_by" part
#####
HistConditionRegin<-aggregateList %>% mutate(LogBin = case_when(Size <= 5 ~ "(.5, 5]",
                        Size<= 10 ~ "(5, 10]",
                        Size<= 100    ~ "(10, 100]",
                        Size<= 1000   ~ "(100, 1000]",
                        Size> 1000  ~ paste0("(1000, ",bquote("\U221E"), ")"))) %>%
  group_by(Species,Condition,TimePoint,Region)%>% 
  mutate(TotalBiomass = sum(Size), TotalFrequency = n()) %>% ungroup() %>%
  group_by(Species,Condition,TimePoint,Region,LogBin)%>%
  mutate(BinBiomass = sum(Size), BinFrequency = n()) %>% ungroup() %>%
  mutate(NormalizedFrequency = BinFrequency/TotalFrequency*100, NormalizedBiomass = BinBiomass/TotalBiomass*100)


HistConditionRegin$LogBin <- factor(HistConditionRegin$LogBin, levels = c("(.5, 5]", "(5, 10]","(10, 100]", "(100, 1000]", paste0("(1000, ",bquote("\U221E"), ")")),labels = c(levels = c("(.5, 5]", "(5, 10]","(10, 100]", "(100, 1000]", paste0("(1000, ",bquote("\U221E"), ")"))))
#Summary data frame
HistCondRegionSum<-HistConditionRegin %>%
  group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition,Region,LogBin,NormalizedFrequency,NormalizedBiomass) %>% 
  summarize() %>% unique()%>%ungroup() %>%
  group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition,Region) %>% 
  mutate(checkSumFreq =sum(NormalizedFrequency), checkSumBiomass = sum(NormalizedBiomass))
#####

#Stats for aggregate frequency and biomass
#####
##Mono vs Co
###
PaMono5<-HistReplicateSummary %>% filter(Species == "P. aeruginosa" & TimePoint == "Day 4", Strain == "wt", Culture == "mono",LogBin == "(.5, 5]")
PaCo5<-HistReplicateSummary %>% filter(Species == "P. aeruginosa" & TimePoint == "Day 4", Strain == "wt", Culture == "co",LogBin == "(.5, 5]")
PaMono10<-HistReplicateSummary %>% filter(Species == "P. aeruginosa" & TimePoint == "Day 4", Strain == "wt", Culture == "mono",LogBin == "(5, 10]")
PaCo10<-HistReplicateSummary %>% filter(Species == "P. aeruginosa" & TimePoint == "Day 4", Strain == "wt", Culture == "co",LogBin == "(5, 10]")
PaMono100<-HistReplicateSummary %>% filter(Species == "P. aeruginosa" & TimePoint == "Day 4", Strain == "wt", Culture == "mono",LogBin == "(10, 100]")
PaCo100<-HistReplicateSummary %>% filter(Species == "P. aeruginosa" & TimePoint == "Day 4", Strain == "wt", Culture == "co",LogBin == "(10, 100]")

PaMonoCo5BiomassTtest <-t.test(x = PaMono5$NormalizedBiomass, y = PaCo5$NormalizedBiomass, paired = F)
PaMonoCo5FreqTtest    <-t.test(x = PaMono5$NormalizedFrequency, y = PaCo5$NormalizedFrequency, paired = F)
PaMonoCo10FreqTtest   <-t.test(x = PaMono10$NormalizedFrequency, y = PaCo10$NormalizedFrequency, paired = F)
PaMonoCo100FreqTtest  <-t.test(x = PaMono100$NormalizedFrequency, y = PaCo100$NormalizedFrequency, paired = F)


SaMono5<-HistReplicateSummary %>% filter(Species == "S. aureus",TimePoint =="Day 4",Strain == "Sa",Culture == "mono",LogBin == "(.5, 5]")
SaCo5<-HistReplicateSummary %>% filter(Species == "S. aureus"&TimePoint =="Day 4",Strain == "wt",Culture == "co",LogBin == "(.5, 5]")
SaMono10<-HistReplicateSummary %>% filter(Species == "S. aureus",TimePoint =="Day 4",Strain == "Sa",Culture == "mono",LogBin == "(5, 10]")
SaCo10<-HistReplicateSummary %>% filter(Species == "S. aureus"&TimePoint =="Day 4",Strain == "wt",Culture == "co",LogBin == "(5, 10]")
SaMono100<-HistReplicateSummary %>% filter(Species == "S. aureus",TimePoint =="Day 4",Strain == "Sa",Culture == "mono",LogBin == "(10, 100]")
SaCo100<-HistReplicateSummary %>% filter(Species == "S. aureus"&TimePoint =="Day 4",Strain == "wt",Culture == "co",LogBin == "(10, 100]")

SaMonoCo5BiomassTtest <-t.test(x = SaMono5$NormalizedBiomass, y = SaCo5$NormalizedBiomass, paired = F)
SaMonoCo5FreqTtest    <-t.test(x = SaMono5$NormalizedFrequency, y = SaCo5$NormalizedFrequency, paired = F)
SaMonoCo10FreqTtest   <-t.test(x = SaMono10$NormalizedFrequency, y = SaCo10$NormalizedFrequency, paired = F)
SaMonoCo100FreqTtest  <-t.test(x = SaMono100$NormalizedFrequency, y = SaCo100$NormalizedFrequency, paired = F)

tTestFigs1CDData<-list(PaMonoCo5BiomassTtest,PaMonoCo5FreqTtest,PaMonoCo10FreqTtest,PaMonoCo100FreqTtest,
                       SaMonoCo5BiomassTtest,SaMonoCo5FreqTtest,SaMonoCo10FreqTtest,SaMonoCo100FreqTtest)
tTestFigs1CDTable<-bind_rows(map(tTestFigs1CDData, TtestTable))
### Edge vs Core only co-cultures
#####
Pawt5E<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint=="Day 4",Strain == "wt", Culture == "co",LogBin == "(.5, 5]",Region == "edge")
Pawt5C<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain == "wt",Culture == "co",LogBin == "(.5, 5]",Region == "core")
Pawt10E<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain== "wt",Culture == "co",LogBin == "(5, 10]",Region == "edge")
Pawt10C<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain== "wt",Culture == "co",LogBin == "(5, 10]",Region == "core")
Pawt100E<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain=="wt",Culture=="co",LogBin == "(10, 100]",Region == "edge")
Pawt100C<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain=="wt",Culture=="co",LogBin == "(10, 100]",Region == "core")

Sawt5E<-HistReplicateSummary%>%filter(Species == "S. aureus",TimePoint == "Day 4", Strain == "wt", Culture=="co",LogBin =="(.5, 5]",Region == "edge")
Sawt5C<-HistReplicateSummary%>%filter(Species == "S. aureus",TimePoint == "Day 4", Strain == "wt", Culture=="co",LogBin =="(.5, 5]",Region == "core")
Sawt10E<-HistReplicateSummary%>%filter(Species == "S. aureus",TimePoint == "Day 4", Strain == "wt", Culture == "co",LogBin == "(5, 10]",Region == "edge")
Sawt10C<-HistReplicateSummary%>%filter(Species == "S. aureus",TimePoint == "Day 4", Strain == "wt", Culture == "co",LogBin == "(5, 10]",Region == "core")
Sawt100E<-HistReplicateSummary%>%filter(Species == "S. aureus",TimePoint == "Day 4",Strain == "wt", Culture=="co",LogBin=="(10, 100]",Region== "edge")
Sawt100C<-HistReplicateSummary %>% filter(Species == "S. aureus",TimePoint=="Day 4",Strain=="wt",Culture == "co",LogBin == "(10, 100]",Region == "core")

Pawt5CorEdBioTtest     <-t.test(x = Pawt5E$NormalizedBiomass, y = Pawt5C$NormalizedBiomass, paired = F)
Pawt5CorEdFreqTtest    <-t.test(x = Pawt5E$NormalizedFrequency, y = Pawt5C$NormalizedFrequency, paired = F)
Pawt10CorEdFreqTtest   <-t.test(x = Pawt10E$NormalizedFrequency, y = Pawt10C$NormalizedFrequency, paired = F)
Pawt100CorEdFreqTtest  <-t.test(x = Pawt100E$NormalizedFrequency, y = Pawt100C$NormalizedFrequency, paired = F)

Sawt5CorEdBioTtest     <-t.test(x = Sawt5E$NormalizedBiomass, y = Sawt5C$NormalizedBiomass, paired = F)
Sawt5CorEdFreqTtest    <-t.test(x = Sawt5E$NormalizedFrequency, y = Sawt5C$NormalizedFrequency, paired = F)
Sawt10CorEdFreqTtest   <-t.test(x = Sawt10E$NormalizedFrequency, y = Sawt10C$NormalizedFrequency, paired = F)
Sawt100CorEdFreqTtest  <-t.test(x = Sawt100E$NormalizedFrequency, y = Sawt100C$NormalizedFrequency, paired = F)

tTestFigs1CDDataCorEdge<-list(Pawt5CorEdBioTtest,Pawt5CorEdFreqTtest,Pawt10CorEdFreqTtest,Pawt100CorEdFreqTtest,
                       Sawt5CorEdBioTtest,Sawt5CorEdFreqTtest,Sawt10CorEdFreqTtest,Sawt100CorEdFreqTtest)

tTestFigs1CDTableCorEdge<-bind_rows(map(tTestFigs1CDDataCorEdge, TtestTable))

##wt vs mutants
# Compute the analysis of variance 
Pabiomass5Aov <- aov(NormalizedBiomass ~ Strain, data = HistReplicateSummary%>%
                     filter(Species == "P. aeruginosa",TimePoint == "Day 4",Culture == "co",LogBin == "(.5, 5]"))
Pafrequency5Aov <- aov(NormalizedFrequency ~ Strain, data = HistReplicateSummary%>%
                       filter(Species == "P. aeruginosa",TimePoint == "Day 4",Culture == "co",LogBin == "(.5, 5]"))
Pafrequency10Aov <- aov(NormalizedFrequency ~ Strain, data = HistReplicateSummary%>%
                       filter(Species == "P. aeruginosa",TimePoint == "Day 4",Culture == "co",LogBin == "(5, 10]"))
Pafrequency100Aov <- aov(NormalizedFrequency ~ Strain, data = HistReplicateSummary%>%
                       filter(Species == "P. aeruginosa",TimePoint == "Day 4",Culture == "co",LogBin == "(10, 100]"))
##None of the Pa are significant
Sabiomass5Aov <- aov(NormalizedBiomass ~ Strain, data = HistReplicateSummary%>%
                     filter(Species == "S. aureus",TimePoint == "Day 4",Culture == "co",LogBin == "(.5, 5]")) 
Safrequency5Aov <- aov(NormalizedFrequency ~ Strain, data = HistReplicateSummary%>%
                       filter(Species == "S. aureus",TimePoint == "Day 4",Culture == "co",LogBin == "(.5, 5]"))
Safrequency10Aov <- aov(NormalizedFrequency ~ Strain, data = HistReplicateSummary%>%
                       filter(Species == "S. aureus",TimePoint == "Day 4",Culture == "co",LogBin == "(5, 10]"))
Safrequency100Aov <- aov(NormalizedFrequency ~ Strain, data = HistReplicateSummary%>%
                       filter(Species == "S. aureus",TimePoint == "Day 4",Culture == "co",LogBin == "(10, 100]"))

# Summary of the analysis #only showing significant values
summary(Sabiomass5Aov)#*p = 0.07
TukeyHSD(Sabiomass5Aov)#*p pqsL-wt 0.077
summary(Safrequency10Aov)#*p = 0.005
TukeyHSD(Safrequency10Aov)#*p pqsL-wt 0.003

#bundling up bin and edge
HistReplicateSummary$StrainRegion <- paste(HistReplicateSummary$Region, "-", HistReplicateSummary$Strain)

Pabiomass5AovSR <- aov(NormalizedBiomass ~ StrainRegion, data = HistReplicateSummary%>%
                     filter(Species == "P. aeruginosa",TimePoint == "Day 4",Culture == "co",LogBin == "(.5, 5]"))
Pafrequency5AovSR <- aov(NormalizedFrequency ~ StrainRegion, data = HistReplicateSummary%>%
                       filter(Species == "P. aeruginosa",TimePoint == "Day 4",Culture == "co",LogBin == "(.5, 5]"))
Pafrequency10AovSR <- aov(NormalizedFrequency ~ StrainRegion, data = HistReplicateSummary%>%
                       filter(Species == "P. aeruginosa",TimePoint == "Day 4",Culture == "co",LogBin == "(5, 10]"))
Pafrequency100AovSR <- aov(NormalizedFrequency ~ StrainRegion, data = HistReplicateSummary%>%
                       filter(Species == "P. aeruginosa",TimePoint == "Day 4",Culture == "co",LogBin == "(10, 100]"))
##None of the Pa are significant
Sabiomass5AovSR <- aov(NormalizedBiomass ~ StrainRegion, data = HistReplicateSummary%>%
                     filter(Species == "S. aureus",TimePoint == "Day 4",Culture == "co",LogBin == "(.5, 5]")) 
Safrequency5AovSR <- aov(NormalizedFrequency ~ StrainRegion, data = HistReplicateSummary%>%
                       filter(Species == "S. aureus",TimePoint == "Day 4",Culture == "co",LogBin == "(.5, 5]"))
Safrequency10AovSR <- aov(NormalizedFrequency ~ StrainRegion, data = HistReplicateSummary%>%
                       filter(Species == "S. aureus",TimePoint == "Day 4",Culture == "co",LogBin == "(5, 10]"))
Safrequency100AovSR <- aov(NormalizedFrequency ~ StrainRegion, data = HistReplicateSummary%>%
                       filter(Species == "S. aureus",TimePoint == "Day 4",Culture == "co",LogBin == "(10, 100]"))
summary(Sabiomass5AovSR)#
TukeyHSD(Sabiomass5AovSR)#*p core wt vs core pqsL 0.08, edge phz vs core pqsL 0.04, edge wt core pqsL .08
summary(Safrequency5AovSR)# nope
summary(Safrequency10AovSR)#yup
TukeyHSD(Safrequency10AovSR)# core pqsL VS core wt 0.01, vs edge phz 0.03 edge pqsL 0.06, edge wt 0.03 
summary(Safrequency100AovSR)

#now compute comparison edge vs core
##Pa
PaPhz5E<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint=="Day 4",Strain == "phz", Culture == "co",LogBin == "(.5, 5]",Region == "edge")
PaPhz5C<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain == "phz",Culture == "co",LogBin == "(.5, 5]",Region == "core")
PaPhz10E<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain== "phz",Culture == "co",LogBin == "(5, 10]",Region == "edge")
PaPhz10C<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain== "phz",Culture == "co",LogBin == "(5, 10]",Region == "core")
PaPhz100E<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain=="phz",Culture=="co",LogBin == "(10, 100]",Region == "edge")
PaPhz100C<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain=="phz",Culture=="co",LogBin == "(10, 100]",Region == "core")
PaPqsL5E<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain=="pqsL",Culture == "co",LogBin == "(.5, 5]",Region == "edge")
PaPqsL5C<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain=="pqsL",Culture == "co",LogBin == "(.5, 5]",Region == "core")
PaPqsL10E<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint=="Day 4",Strain=="pqsL",Culture == "co",LogBin == "(5, 10]",Region == "edge")
PaPqsL10C<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint=="Day 4",Strain =="pqsL",Culture =="co",LogBin == "(5, 10]",Region == "core")
PaPqsL100E<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint=="Day 4",Strain=="pqsL",Culture=="co",LogBin =="(10, 100]",Region == "edge")
PaPqsL100C<-HistReplicateSummary%>% filter(Species=="P. aeruginosa",TimePoint== "Day 4",Strain=="pqsL",Culture=="co",LogBin=="(10, 100]",Region == "core")

PaPhz5CorEdBioTtest     <-t.test(x = PaPhz5E$NormalizedBiomass, y = PaPhz5C$NormalizedBiomass, paired = F)
PaPhz5CorEdFreqTtest    <-t.test(x = PaPhz5E$NormalizedFrequency, y = PaPhz5C$NormalizedFrequency, paired = F)
PaPhz10CorEdFreqTtest   <-t.test(x = PaPhz10E$NormalizedFrequency, y = PaPhz10C$NormalizedFrequency, paired = F)
PaPhz100CorEdFreqTtest  <-t.test(x = PaPhz100E$NormalizedFrequency, y = PaPhz100C$NormalizedFrequency, paired = F)
PaPqsL5CorEdBioTtest     <-t.test(x = PaPqsL5E$NormalizedBiomass, y = PaPqsL5C$NormalizedBiomass, paired = F)
PaPqsL5CorEdFreqTtest    <-t.test(x = PaPqsL5E$NormalizedFrequency, y = PaPqsL5C$NormalizedFrequency, paired = F)
PaPqsL10CorEdFreqTtest   <-t.test(x = PaPqsL10E$NormalizedFrequency, y = PaPqsL10C$NormalizedFrequency, paired = F)
PaPqsL100CorEdFreqTtest  <-t.test(x = PaPqsL100E$NormalizedFrequency, y = PaPqsL100C$NormalizedFrequency, paired = F)
##Sa
SaPhz5E<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "phz", Culture=="co",LogBin =="(.5, 5]",Region == "edge")
SaPhz5C<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "phz", Culture=="co",LogBin =="(.5, 5]",Region == "core")                                        
SaPqsL5E<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "pqsL", Culture == "co",LogBin == "(.5, 5]",Region == "edge")
SaPqsL5C<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "pqsL", Culture == "co",LogBin == "(.5, 5]",Region == "core")
SaPhz10E<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "phz", Culture == "co",LogBin == "(5, 10]",Region == "edge")
SaPhz10C<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "phz", Culture == "co",LogBin == "(5, 10]",Region == "core")
SaPqsL10E<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "pqsL", Culture == "co",LogBin == "(5, 10]",Region == "edge")
SaPqsL10C<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "pqsL", Culture == "co",LogBin == "(5, 10]",Region == "core")
SaPhz100E<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "phz", Culture == "co",LogBin == "(10, 100]",Region == "edge")
SaPhz100C<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "phz", Culture == "co",LogBin == "(10, 100]",Region == "core")
SaPqsL100E<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "pqsL", Culture == "co",LogBin == "(10, 100]",Region == "edge")
SaPqsL100C<-HistReplicateSummary %>% filter(Species == "S. aureus" & TimePoint == "Day 4", Strain == "pqsL", Culture == "co",LogBin == "(10, 100]",Region == "core")
SaPhz5CorEdBioTtest     <-t.test(x = SaPhz5E$NormalizedBiomass, y = SaPhz5C$NormalizedBiomass, paired = F)
SaPhz5CorEdFreqTtest    <-t.test(x = SaPhz5E$NormalizedFrequency, y = SaPhz5C$NormalizedFrequency, paired = F)
SaPhz10CorEdFreqTtest   <-t.test(x = SaPhz10E$NormalizedFrequency, y = SaPhz10C$NormalizedFrequency, paired = F)
SaPhz100CorEdFreqTtest  <-t.test(x = SaPhz100E$NormalizedFrequency, y = SaPhz100C$NormalizedFrequency, paired = F)
SaPqsL5CorEdBioTtest     <-t.test(x = SaPqsL5E$NormalizedBiomass, y = SaPqsL5C$NormalizedBiomass, paired = F)
SaPqsL5CorEdFreqTtest    <-t.test(x = SaPqsL5E$NormalizedFrequency, y = SaPqsL5C$NormalizedFrequency, paired = F)
SaPqsL10CorEdFreqTtest   <-t.test(x = SaPqsL10E$NormalizedFrequency, y = SaPqsL10C$NormalizedFrequency, paired = F)
SaPqsL100CorEdFreqTtest  <-t.test(x = SaPqsL100E$NormalizedFrequency, y = SaPqsL100C$NormalizedFrequency, paired = F)

tTestFigs2CDData<-list(PaPhz5CorEdBioTtest,PaPhz5CorEdFreqTtest,PaPhz10CorEdFreqTtest,PaPhz100CorEdFreqTtest,
                       PaPqsL5CorEdBioTtest,PaPqsL5CorEdFreqTtest,PaPqsL10CorEdFreqTtest,PaPqsL100CorEdFreqTtest,
                       SaPhz5CorEdBioTtest,SaPhz5CorEdFreqTtest,SaPhz10CorEdFreqTtest,SaPhz100CorEdFreqTtest,
                       SaPqsL5CorEdBioTtest,SaPqsL5CorEdFreqTtest,SaPqsL10CorEdFreqTtest,SaPqsL100CorEdFreqTtest) 

tTestFigs2CDTableCorevsEdge<-bind_rows(map(tTestFigs2CDData, TtestTable))

```

```{r Plot Aggregate size bins}
#Plot Normalized Frequency
#this isn't useful as the normalized Frequency changes with replicate, so it's better to pool all samples together
PlotHistSum<-function(rep.df,cond.df,region.df, y_var, title, colorStrain){
ggplot()+
    geom_point(data = rep.df %>% filter(TimePoint=="Day 4"),
                aes(x=as.factor(LogBin),y=.data[[y_var]], color =.data[[colorStrain]], shape = Region),
               position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75),size=1)+
    geom_point(data = region.df%>% filter(TimePoint=="Day 4"),
               aes(x=as.factor(LogBin),y=.data[[y_var]], color =.data[[colorStrain]],shape = Region),
               size=3, position = position_dodge(width = .75) )+
    geom_point(data = cond.df%>% filter(TimePoint=="Day 4"),
               aes(x=as.factor(LogBin),y=.data[[y_var]],  color =.data[[colorStrain]]),size=4, shape = 3,position = position_dodge(width = .75) )+
    #scale_y_log10(breaks = c(100, 10, 1, .1, .01), labels = c(100, 10, 1, .1, .01))+
    facet_grid(.~Species)+
    scale_shape_manual(values=c(16, 1))+
    ggtitle(title)+
    labs(y = paste("Frequency (%)"),x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    scale_color_brewer(palette = "Set1")+
    theme_cowplot()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}
PlotHistSum(HistReplicateSummary,HistConditionSummary,HistCondRegionSum,"NormalizedFrequency", "Normalized Frequency all sizes", "S. aureus")

####---Figure 1C
PlotHistSum(HistReplicateSummary%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
            HistConditionSummary%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
            HistCondRegionSum%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
            "NormalizedFrequency", "Normalized Frequency per size",  "Culture")

PlotHistSum(HistReplicateSummary%>% filter(Culture =="co"),
            HistConditionSummary%>% filter(Culture =="co"),
            HistCondRegionSum%>% filter(Culture =="co"),
            "NormalizedFrequency", "Normalized Frequency per size bin", "Strain")
#To Show the mono for Pa, one way to do it is to include the species in the filtering and do one plot per species. I dont thnink it's reasonable to do it all in one plot

#Plot normalized Biomass per sample
##Pa
PlotHistRepBioTrend<-function(rep.df,species){
ggplot()+
    geom_line(data = rep.df %>% filter(Species==species),aes(x=as.factor(LogBin),y=NormalizedBiomass, color = Replicate, group = Replicate ),size=1)+
    guides(color = FALSE)+
    facet_grid(Condition~TimePoint)+
    labs(y = "Normalized Biomass",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    ggtitle(paste('Normalized Biomass per Sample', species))+
    theme_cowplot()+
    scale_colour_grey()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5)) }
PlotHistRepBioTrend(HistReplicateSummary, "P. aeruginosa")
PlotHistRepBioTrend(HistReplicateSummary, "S. aureus")
```

```{Aggregates Only, Not currently in use}
#####
#Now only aggregates 5 microns or larger

##Separating the replicates
#####
aggsHistRep<-aggregateList %>% mutate(LogBin = case_when(Size <= 5 ~ 5,
                        Size<= 10 ~ 10,
                        Size<= 100    ~ 100,
                        Size<= 1000   ~ 1000,
                        Size<= 10000  ~ 10000,
                        Size<= 100000 ~ 100000,
                        Size > 100000 ~ 1000000)) %>% filter(!LogBin == 5) %>%
  group_by(Species,Culture,Strain,Condition,TimePoint, Replicate)%>% 
  mutate(TotalBiomass = sum(Size), TotalFrequency = n()) %>% ungroup() %>% 
  group_by(Species,Culture,Strain,Condition,TimePoint, Replicate, LogBin)%>%
  mutate(BinBiomass = sum(Size), BinFrequency = n()) %>% ungroup() %>%
  mutate(NormalizedFrequency = BinFrequency/TotalFrequency*100, NormalizedBiomass = BinBiomass/TotalBiomass*100)

##Summary df
aggsHistRepSum<-aggsHistRep %>% group_by(Species,Culture,Strain,Condition,TimePoint, Replicate, LogBin,NormalizedFrequency,NormalizedBiomass) %>% summarize() %>%  unique()%>%ungroup() %>%  group_by(Species,Culture,Strain,Condition,TimePoint, Replicate) %>% mutate(checkSumFreq =sum(NormalizedFrequency), checkSumBiomass = sum(NormalizedBiomass))
#####
##Pooling replicates together
#####
aggsHistCond<-aggregateList %>% mutate(LogBin = case_when(Size <= 5 ~ 5,
                        Size<= 10 ~ 10,
                        Size<= 100    ~ 100,
                        Size<= 1000   ~ 1000,
                        Size<= 10000  ~ 10000,
                        Size<= 100000 ~ 100000,
                        Size > 100000 ~ 1000000)) %>% filter(!LogBin == 5) %>%
  group_by(Species,Culture,Strain,Condition,TimePoint)%>% 
  mutate(TotalBiomass=sum(Size),TotalFrequency=n()) %>% ungroup() %>% 
  group_by(Species,Culture,Strain,Condition,TimePoint, LogBin)%>%
  mutate(BinBiomass = sum(Size), BinFrequency = n()) %>% ungroup() %>%
  mutate(NormalizedFrequency = BinFrequency/TotalFrequency*100, NormalizedBiomass = BinBiomass/TotalBiomass*100)

##Summary df
aggsHistCondSum<-aggsHistCond %>% 
  group_by(Species,Culture,Strain,Condition,TimePoint, LogBin,NormalizedFrequency,NormalizedBiomass) %>%
  summarize() %>%  unique()%>%ungroup() %>%
  group_by(Species,Culture,Strain,Condition,TimePoint) %>%
  mutate(checkSumFreq =sum(NormalizedFrequency), checkSumBiomass = sum(NormalizedBiomass))%>%ungroup()

#now plot it
#normalized frequency

PlotHistSum(aggsHistRepSum,aggsHistCondSum,"NormalizedFrequency", "Normalized Frequency aggregates only")
PlotHistSum(aggsHistRepSum,aggsHistCondSum,"NormalizedBiomass","Normalized Biomass aggregates only")
PlotHistRepBioTrend(aggsHistRepSum, "P. aeruginosa")
PlotHistRepBioTrend(aggsHistRepSum, "S. aureus")

#####
```
```{r Aggregates vs Planktonics}
#Planktonic vs aggregates
#####
#Add agregation value to the dataframe 
##Normalize using replicates
HistReplicate<-HistReplicate %>%  mutate(Aggregation = if_else(LogBin == "(.5, 5]" ,"Planktonic", "Aggregate")) %>%
  group_by(Species,SampleCode, Aggregation)%>% 
  mutate(AgPlBiomass = sum(Size), AgPlFreq = n()) %>% ungroup() %>%
  mutate(AgPlNormFrequency = AgPlFreq/TotalFrequency*100, AgPlNormBiomass = AgPlBiomass/TotalBiomass*100)
#Collapse to only values per replicate
plankAggHistRep<-HistReplicate %>% 
  group_by(SampleCode,Species,SaStrain,Strain,Culture,TimePoint,Condition,Replicate,Region,Aggregation,AgPlNormFrequency,AgPlNormBiomass) %>% 
  summarize() %>%  unique()%>%ungroup() %>%  
  group_by(SampleCode,Species,SaStrain,Strain,Culture,TimePoint,Condition,Replicate,Region) %>% mutate(checkAggFreq =sum(AgPlNormFrequency), checkAggBiomass = sum(AgPlNormBiomass))

plankAggHistRepStats<-plankAggHistRep %>%
  group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition,Aggregation)%>%
  summarize(MeanFreq = mean(AgPlNormFrequency), MeanBiomass = mean(AgPlNormBiomass)) 

##Normalize using Condition 
HistCondition<-HistCondition %>%  mutate(Aggregation = if_else(LogBin == "(.5, 5]", "Planktonic", "Aggregate")) %>%
  group_by(Species,Condition,TimePoint,Aggregation)%>% 
  mutate(AgPlBiomass = sum(Size), AgPlFreq = n()) %>% ungroup() %>%
  mutate(AgPlNormFrequency = AgPlFreq/TotalFrequency*100, AgPlNormBiomass = AgPlBiomass/TotalBiomass*100)
#Collapse to only values per replicate
plankAggHistCond<-HistCondition %>% 
  group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition,Aggregation,AgPlNormFrequency,AgPlNormBiomass) %>%
  summarize() %>%  unique()%>%ungroup() %>%  
  group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition) %>% mutate(checkAggFreq =sum(AgPlNormFrequency), checkAggBiomass = sum(AgPlNormBiomass))

##Normalize using Condition and region
HistConditionRegin<-HistConditionRegin %>%  mutate(Aggregation = if_else(LogBin == "(.5, 5]", "Planktonic", "Aggregate")) %>%
  group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition,Region,Aggregation)%>% 
  mutate(AgPlBiomass = sum(Size), AgPlFreq = n()) %>% ungroup() %>%
  mutate(AgPlNormFrequency = AgPlFreq/TotalFrequency*100, AgPlNormBiomass = AgPlBiomass/TotalBiomass*100)
#Collapse to only values per condition and Replicate
plankAggHistCondReg<-HistConditionRegin %>% 
  group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition,Region,Aggregation,AgPlNormFrequency,AgPlNormBiomass) %>%
  summarize() %>%  unique()%>%ungroup() %>%
  group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition,Region) %>% mutate(checkAggFreq =sum(AgPlNormFrequency), checkAggBiomass = sum(AgPlNormBiomass))
```

```{r figures 1D and 2D Plot Aggregate vs planktonics}

#Plot Frequency
PlotAggPlankSpecies<-function(rep.df,cond.df,region.df, y_var, title, species, colorStrain, facet){
ggplot()+
    geom_point(data = rep.df %>% filter(TimePoint=="Day 4")%>% filter(Species == species),
                aes(x=as.factor(Aggregation),y=.data[[y_var]], color =.data[[colorStrain]], shape = Region),
               position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75),size=1)+
    geom_point(data = region.df%>% filter(TimePoint=="Day 4")%>% filter(Species == species),
               aes(x=as.factor(Aggregation),y=.data[[y_var]], color =.data[[colorStrain]],shape = Region),
               size=3, position = position_dodge(width = .75) )+
    geom_point(data = cond.df%>% filter(TimePoint=="Day 4") %>% filter(Species == species),
               aes(x=as.factor(Aggregation),y=.data[[y_var]],  color =.data[[colorStrain]]),size=4, shape = 3,position = position_dodge(width = .75) )+
    scale_y_log10(breaks = c(100, 10, 1, .1, .01), labels = c(100, 10, 1, .1, .01))+
    facet_grid(.~.data[[facet]])+
    scale_shape_manual(values=c(16, 1))+
    ggtitle(title)+
    labs(y = paste("Biomass Contribution (%)"),x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    scale_color_brewer(palette = "Set1")+
    theme_cowplot()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}
PlotAggPlank<-function(rep.df, y_var, title, colorStrain, facet){
ggplot()+
    geom_point(data = rep.df %>% filter(TimePoint=="Day 4" & Aggregation == "Planktonic"),
                aes(x=.data[[facet]],y=.data[[y_var]], color =.data[[colorStrain]], shape = Region),
               position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75),size=1)+
    #geom_point(data = region.df%>% filter(TimePoint=="Day 4"& Aggregation == "Planktonic"),
    #           aes(x=.data[[facet]],y=.data[[y_var]], color =.data[[colorStrain]],shape = Region),
    #           size=3, position = position_dodge(width = .75) )+
    #geom_point(data = cond.df%>% filter(TimePoint=="Day 4"& Aggregation == "Planktonic"),
    #           aes(x=.data[[facet]],y=.data[[y_var]],  color =.data[[colorStrain]]),size=4, shape = 3,position = position_dodge(width = .75) )+
    #scale_y_log10(breaks = c(100, 10, 1, .1, .01), labels = c(100, 10, 1, .1, .01))+
    #facet_grid(.~.data[[facet]])+
    scale_shape_manual(values=c(16, 1))+
    ggtitle(title)+
    labs(y = expression(atop("Planktonic cells", "biomass contribution (%)")))+
    scale_x_discrete(name ="", breaks = c("P. aeruginosa","S. aureus"), 
                   labels = c(expression(italic("P. aeruginosa")), 
                              expression(italic("S. aureus"))))+
    scale_color_brewer(palette = "Set1")+
    theme_cowplot()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}


###---Figure 1D
#this is the current version but the ones below mmight also work if I want to show Pa monos and not facetting the species
PlotAggPlank(plankAggHistRep%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
             #plankAggHistCond%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
             #plankAggHistCondReg%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
             "AgPlNormBiomass", "Biomass from planktonic cells", "Culture","Species")

test<-plankAggHistRep%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono") %>% filter(TimePoint=="Day 4" & Aggregation == "Planktonic")

PlotAggPlank(plankAggHistRep%>% filter(Culture == "co"),
             plankAggHistCond%>% filter(Culture == "co"),
             plankAggHistCondReg%>% filter(Culture == "co"),
             "AgPlNormBiomass", "Biomass from planktonic cells", "Strain","Species")


#these are the other versions
PlotAggPlankSpecies(plankAggHistRep%>% filter(SaStrain %in% c("Sa mono", "co-wt")),
             plankAggHistCond%>% filter(SaStrain %in% c("Sa mono", "co-wt")),
             plankAggHistCondReg%>% filter(SaStrain %in% c("Sa mono", "co-wt")),
             "AgPlNormBiomass", "Normalized Biomass", "S. aureus", "Culture", "Species")

PlotAggPlankSpecies(plankAggHistRep,
             plankAggHistCond,
             plankAggHistCondReg,
             "AgPlNormBiomass", "Normalized Biomass", "S. aureus", "SaStrain","Species")

PlotAggPlankSpecies(plankAggHistRep,
             plankAggHistCond,
             plankAggHistCondReg,
             "AgPlNormBiomass", "Normalized Biomass", "P. aeruginosa", "Strain","Culture")

#Plot Biomass
ggplot()+
  geom_jitter(data = plankAggHistRep,
              aes(x=as.factor(Aggregation),y=AgPlNormBiomass,  color =Condition ),size=2, height = 0, width = .2, shape = 1)+
  geom_point(data = plankAggHistCond,
             aes(x=as.factor(Aggregation),y=AgPlNormBiomass,  color =Condition),size=5, shape = 16, position = position_dodge2(width = .5)) +
  facet_grid(Species~TimePoint)+
  ggtitle("Normalized Biomass (%) Aggs vs Plank")+
  labs(y = "Normalized Biomass (%)",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+ 
  theme_cowplot()+
  panel_border() +
  scale_color_brewer(palette = "Set1")+
  theme(plot.title = element_text(hjust = 0.3)) 
#####
```

```{r Figures from Pasa SCFM2 Paper}
#Biomass contribution of Planktonic vs Aggregates
#####
#Do stats on the df that has each replicate
plankAggHistSummary<-plankAggHistRep %>% group_by(Species,TimePoint,Culture,Strain,Condition,Aggregation) %>%
  summarise(MeanFreq = mean(AgPlNormFrequency), SEFreq = std.error(AgPlNormFrequency), MeanBiomass = mean(AgPlNormBiomass),
            SEBiomass = std.error(AgPlNormBiomass))

#Plot using the code from the paper
PlotAggregateBiomassContribution<-function(species){
ggplot()+
  geom_col(data = plankAggHistSummary %>% filter(Aggregation=="Aggregate") %>% filter(Species==species), aes(x=Strain,y=MeanBiomass, fill = Culture),
           size=3,position = position_dodge( width = .9))+
  geom_jitter(data = plankAggHistRep%>% filter(Aggregation=="Aggregate")%>% filter(Species==species), aes(x=Strain,y=AgPlNormBiomass, group = Culture),
              shape = 1,size=2,position = position_dodge(width = .9),show.legend = FALSE)+
  geom_errorbar(data = plankAggHistSummary%>% filter(Aggregation=="Aggregate")%>% filter(Species==species), aes(x=Strain,ymin=(MeanBiomass-SEBiomass), ymax = (MeanBiomass+SEBiomass), group = Culture),width = 0, size=.5,position = position_dodge(width = .9))+
  scale_y_continuous(limits = c(0,103),expand = expand_scale(mult = c(0, 0)))+
  facet_grid(.~TimePoint)+
  scale_fill_grey()+
  labs(title = '', x = "", y = "Aggregate Biomass contribution (%)")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
        strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
        axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,0,0),size=13),
        axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11),
        legend.title = element_text(size=13),legend.text = element_text(size = 11),
        legend.position = c(.25, 0.60))
}
PlotAggregateBiomassContribution("P. aeruginosa")
PlotAggregateBiomassContribution("S. aureus")

#####
#Normalized Frequency and Biomass contribution of Aggregate bins
#####
#Collapse to data per condition
AggsOnlySummary<-aggsHistRepSum %>% group_by(Species,TimePoint,Culture, Strain, Condition,LogBin) %>%
  summarise(MeanFreq = mean(NormalizedFrequency), SEFreq = std.error(NormalizedFrequency), MeanBiomass = mean(NormalizedBiomass),
            SEBiomass = std.error(NormalizedBiomass))
#Plot Frequency using code from the paper
PlotFrequencyAggregateSize<-function(species){
ggplot()+
    geom_col(data = AggsOnlySummary %>% filter(Species == species), aes(x=as.factor(LogBin),y=MeanFreq,  fill =Condition ),size=4,position = position_dodge( width = .9))+
    geom_jitter(data = aggsHistRepSum%>% filter(Species == species), aes(x=as.factor(LogBin),y=NormalizedFrequency, group = Condition),shape = 1,size=2,position = position_dodge( width = .9))+
    geom_errorbar(data = AggsOnlySummary%>% filter(Species == species),aes(x=as.factor(LogBin),ymin=(MeanFreq-SEFreq), ymax = (MeanFreq+SEFreq), group = Condition),width = 0, size= .5,position = position_dodge( width = .9))+
    facet_grid(.~TimePoint)+
    labs(fill = "",y = "Aggregates Frequency per bin (% of total)",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    #guides(color = FALSE)+
    #scale_y_continuous(limits = c(0,180), expand = expand_scale(mult = c(0, 0)))+
    theme_half_open()+
    scale_fill_brewer(palette = "Set1")+
    theme(plot.title = element_text(hjust = 0.5),
          strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facets
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
          plot.margin = unit(c(0,.5,0,.5), "cm"),
          axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,0,0),size=11),
          axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,2,2,0),size=11),
          legend.title = element_text(size=13),legend.text = element_text(size = 11),
          legend.position = c(0.79, 0.80))
}
PlotFrequencyAggregateSize("S. aureus")
PlotFrequencyAggregateSize("P. aeruginosa")#add culture to facets

PlotFrequencyAggregateSize2<-function(species){
ggplot()+
    geom_col(data = aggsHistCondSum %>% filter(Species == species), aes(x=as.factor(LogBin),y=NormalizedFrequency,  fill =Condition ),size=4,position = position_dodge( width = .9))+
    geom_jitter(data = aggsHistRepSum%>% filter(Species == species), aes(x=as.factor(LogBin),y=NormalizedFrequency, group = Condition),shape = 1,size=2,position = position_dodge( width = .9))+
    #geom_errorbar(data = AggsOnlySummary%>% filter(Species == species),aes(x=as.factor(LogBin),ymin=(MeanFreq-SEFreq), ymax = (MeanFreq+SEFreq), group = Condition),width = 0, size= .5,position = position_dodge( width = .9))+
    facet_grid(.~TimePoint)+
    labs(fill = "",y = "Aggregates Frequency per bin (% of total)",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    #guides(color = FALSE)+
    #scale_y_continuous(limits = c(0,180), expand = expand_scale(mult = c(0, 0)))+
    theme_half_open()+
    scale_fill_brewer(palette = "Set1")+
    theme(plot.title = element_text(hjust = 0.5),
          strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facets
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
          plot.margin = unit(c(0,.5,0,.5), "cm"),
          axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,0,0),size=11),
          axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,2,2,0),size=11),
          legend.title = element_text(size=13),legend.text = element_text(size = 11),
          legend.position = c(0.79, 0.80))
}
PlotFrequencyAggregateSize2("S. aureus")
PlotFrequencyAggregateSize2("P. aeruginosa")#add culture to facets and change condition for strain on fill and group


#Plot Normalized Biomass #I am not using this one
AggsOnlySummaryRep<-aggsHistRepSum %>% group_by(Species,TimePoint, Replicate, Condition,Culture, Strain,LogBin) %>%
  summarise(MeanFreq = mean(NormalizedFrequency), SEFreq = std.error(NormalizedFrequency), MeanBiomass = mean(NormalizedBiomass),
            SEBiomass = std.error(NormalizedBiomass))
PlotBiomassAggregateSize<-function( species){
ggplot()+
    geom_col(data = AggsOnlySummary %>% filter(Species == species), aes(x=as.factor(LogBin),y=MeanBiomass,  fill =Condition ),size=4,position = position_dodge( width = .9))+
    geom_jitter(data = aggsHistRepSum%>% filter(Species == species), aes(x=as.factor(LogBin),y=NormalizedBiomass, group = Condition),shape = 1,size=1,position = position_dodge( width = .9))+
    geom_errorbar(data = AggsOnlySummary%>% filter(Species == species),aes(x=as.factor(LogBin),ymin=(MeanBiomass-SEBiomass), ymax = (MeanBiomass+SEBiomass), group = Condition),width = 0, size= .5,position = position_dodge( width = .9))+
    facet_grid(.~TimePoint)+
    labs(fill = "",y = "Biomass contribution per bin (% of total)",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    #guides(color = FALSE)+
    scale_y_continuous(limits = c(0,100), expand = expand_scale(mult = c(0, 0)))+
    scale_fill_brewer(palette = "Set1")+
    theme_half_open()+
    theme(plot.title = element_text(hjust = 0.5),
          strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facets
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
          plot.margin = unit(c(0,.5,0,.5), "cm"),
          axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,0,0),size=11),
          axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,2,2,0),size=11),
          legend.title = element_text(size=13),legend.text = element_text(size = 11),
          legend.position = c(0.79, 0.80))
}
PlotBiomassAggregateSize("P. aeruginosa")
PlotBiomassAggregateSize("S. aureus")

#the other way to do it is using aggsHistCondSum and normalized biomass
PlotBiomassAggregateSize2<-function( species){
ggplot()+
    geom_col(data = aggsHistCondSum %>% filter(Species == species), aes(x=as.factor(LogBin),y=NormalizedBiomass,  fill =Condition ),size=4,position = position_dodge( width = .9))+
    geom_jitter(data = aggsHistRepSum%>% filter(Species == species), aes(x=as.factor(LogBin),y=NormalizedBiomass, group = Condition),shape = 1,size=1,position = position_dodge( width = .9))+
    #geom_errorbar(data = aggsHistCondSum%>% filter(Species == species),aes(x=as.factor(LogBin),ymin=(MeanBiomass-SEBiomass), ymax = (MeanBiomass+SEBiomass), group = Condition),width = 0, size= .5,position = position_dodge( width = .9))+
    facet_grid(.~TimePoint)+
    labs(fill = "",y = "Biomass contribution per bin (% of total)",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    #guides(color = FALSE)+
    scale_y_continuous(limits = c(0,100), expand = expand_scale(mult = c(0, 0)))+
    scale_fill_brewer(palette = "Set1")+
    theme_half_open()+
    theme(plot.title = element_text(hjust = 0.5),
          strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facets
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
          plot.margin = unit(c(0,.5,0,.5), "cm"),
          axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,0,0),size=11),
          axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,2,2,0),size=11),
          legend.title = element_text(size=13),legend.text = element_text(size = 11),
          legend.position = c(0.79, 0.80))
}
PlotBiomassAggregateSize2("P. aeruginosa")
PlotBiomassAggregateSize2("S. aureus")
#####
```

```{r biomass per slice}
#this was taken from "Microscopy data clean.Rmd" 
GetSliceData<-function(){#import all experiments at once
  folder<- '/Volumes/raw_data/Confocal/Carolyn/2020/Chronic wounds/Results per slice'
   fileList<-list.files(path = folder, full.names = TRUE)
   growthDf<-data.frame()
   for (aggList in 1:length(fileList)){
     fileName<-str_split(basename(fileList[aggList]), "\\.")[[1]][1]#this selects the base file name and removes the ".csv"
     attrList<-str_split(fileName,"_")[[1]]
     growthDf<-rbind(growthDf,ReadSliceFile(fileList[aggList],attrList[2],attrList[1],attrList[3], fileName))
     }
   return(growthDf)
}
  
ReadSliceFile<-function(file, timepoint, condition, replicate, sampleCode){#make a dataframe of the aggregate size list and add experimental parameters
  print(file)
   datos <-read.csv(file, header = F)  
   colnames(datos)<-c('Biomass', 'Channel', 'Slice') 
   datos<-datos %>% mutate(TimePoint = timepoint) 
   datos<-datos %>% mutate(Condition = condition)
   datos<-datos %>% mutate(Replicate = replicate)
   datos<-datos %>% mutate(SampleCode = sampleCode)
   datos$Replicate<-as.factor(datos$Replicate)
   datos$Condition<-as.factor(datos$Condition)
   datos$TimePoint<-as.factor(datos$TimePoint)
   datos$SampleCode<-as.factor(datos$SampleCode)
   return(datos)
}

#Input data
#####
#get data from csv file
slicedData<-GetSliceData()
 #get metadata
metaData.df <-read.csv('/Volumes/raw_data/Confocal/Carolyn/2020/Chronic wounds/images metadata.csv', header = TRUE)
metaData.df$SampleCode<-as.factor(metaData.df$SampleCode)

#merge files
metaData.df<-metaData.df %>% select(SampleCode, mouse, Position, size, Region, Zdim, xyDim,xySize)
sliceDataMeta<-metaData.df %>%  merge(slicedData, by = "SampleCode")
#clean up
remove <- bind_rows(sliceDataMeta %>% filter(Channel == 2 & Condition == "mono"),
                    sliceDataMeta %>% filter(Channel == 1 & Condition == "pawt"),
                    sliceDataMeta %>% filter(Channel == 1 & Condition == "paphz"),
                    sliceDataMeta %>% filter(Channel == 1 & Condition == "papqsL"))

sliceDataMeta <- anti_join(sliceDataMeta, remove)

sliceDataMeta<-sliceDataMeta %>% filter(!SampleCode == "mono_d1_03")
sliceDataMeta<-sliceDataMeta %>% filter(!SampleCode == "phz_d4_14") #didnt make it to this dataset but still making sure
sliceDataMeta<-sliceDataMeta %>% filter(!SampleCode == "pqsL_d4_02")
sliceDataMeta<-sliceDataMeta %>% filter(!SampleCode == "pqsL_d4_04")
sliceDataMeta<-sliceDataMeta %>% filter(!SampleCode == "pqsL_d4_10")
sliceDataMeta<-sliceDataMeta %>% filter(!SampleCode == "wt_d4_07")
sliceDataMeta<-sliceDataMeta %>% filter(!SampleCode == "papqsL_d4_02")
sliceDataMeta<-sliceDataMeta %>% filter(!SampleCode == "pawt_d4_05")
sliceDataMeta<-sliceDataMeta %>% filter(!SampleCode == "phz_d4_06")

#rename variables
sliceDataMeta<-sliceDataMeta %>% mutate(Species = recode(Channel,"1" ='S. aureus',"2" ='P. aeruginosa',"3" ='host'))
sliceDataMeta$Condition<- factor(sliceDataMeta$Condition, levels = c("mono", "pawt","papqsL", "paphz", "wt", "pqsL", "phz"),
                                  labels = c('Sa mono', 'Pa wt mono','pqsL mono','phz mono','wt co', 'pqsL co', 'phz co'))
sliceDataMeta$TimePoint <- factor(sliceDataMeta$TimePoint, levels = c("d1", "d4"),labels = c('Day 1','Day 4'))
sliceDataMeta<-sliceDataMeta %>% mutate(Culture = recode(Condition, 'Sa mono' = "mono", 'Pa wt mono' = "mono",'pqsL mono'= "mono",'phz mono'= "mono",'wt co'= "co", 'pqsL co'= "co", 'phz co'= "co"))
sliceDataMeta<-sliceDataMeta%>% mutate(Strain = recode(Condition, 'Sa mono' = "Sa", 'Pa wt mono' = "wt",'pqsL mono'= "pqsL",'phz mono'= "phz",'wt co'= "wt", 'pqsL co'= "pqsL", 'phz co'= "phz"))
#add useful metrics
sliceDataMeta<-sliceDataMeta%>% filter(!Channel == "3") %>% mutate(Height = Zdim*Slice) %>% group_by(SampleCode)%>% mutate(MaxHeight = max(Height)) 
#calculate relative biomass
##For all samples

sliceDataMetaAll<-sliceDataMeta%>% group_by(SampleCode, Channel) %>% mutate(TotalBiomass = sum(Biomass)) %>% ungroup() %>% mutate(NormBiomass = Biomass/TotalBiomass*100) 

sliceDataSumary<-sliceDataMeta %>% group_by(SampleCode, TimePoint, Strain, Culture, MaxHeight)%>% summarise() %>% unique()

sliceDataClean<-sliceDataMeta %>% filter(MaxHeight>60) %>% filter(Height<60) %>% filter(TimePoint=="Day 4") %>% group_by(SampleCode, Channel) %>% mutate(TotalBiomass = sum(Biomass)) %>% ungroup() %>% mutate(NormBiomass = Biomass/TotalBiomass*100) 

#####
#Plot Data
#####
ggplot()+
  #geom_point(data = sliceDataMeta ,aes(y=NormBiomass,x=Height, color = Condition, group = Replicate),size=.5)+
  geom_smooth(data = sliceDataMeta ,aes(y=NormBiomass,x=Height, color =Condition),size=2)+
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray")+
  theme_cowplot()+
  scale_color_brewer(palette = "Set1")+
  ylim(0,26)+
  facet_grid(Channel~TimePoint)+
  panel_border() +
  coord_flip()
  theme(plot.title = element_text(hjust = 0.5))
#####
#Filter by Max height of the sample
#####  
  #graph the samples height
  ggplot()+
    geom_col(data = sliceDataSumary %>% filter(TimePoint=="Day 4"),aes(x=SampleCode,y=MaxHeight, color = Strain, fill =Culture ),size=2)+
    geom_hline(yintercept = 50)+
    labs(title ="title")+
    scale_color_brewer(palette = "Set2")+
    scale_fill_brewer(palette = "Set1")+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5))
#####
PlotZsliceSa<-function(){  
  ggplot()+
    geom_smooth(data = sliceDataClean %>% filter(Species == "S. aureus"),aes(y=NormBiomass,x=Height, color = Region),size=2, alpha = .1)+
    #geom_point(data = sliceDataClean%>% filter(Species == species),aes(y=NormBiomass,x=Height, color = Region),size=1, alpha = .5)+
    geom_hline(yintercept = 0, linetype = "dashed", color = "gray")+
    theme_cowplot()+
    scale_color_brewer(palette = "Set1")+
    facet_grid(Strain~.)+
    scale_shape_manual(values = c(1, 3))+
    panel_border() +
    coord_flip()+
    theme(plot.title = element_text(hjust = 0.5))}
PlotZslicePa<-function(){  
  ggplot()+
    geom_smooth(data = sliceDataClean %>% filter(Species == "P. aeruginosa") %>% filter(Culture=="co"),aes(y=NormBiomass,x=Height, color = Region),size=2, alpha = .1)+
    #geom_point(data = sliceDataClean%>% filter(Species == species),aes(y=NormBiomass,x=Height, color = Region),size=1, alpha = .5)+
    geom_hline(yintercept = 0, linetype = "dashed", color = "gray")+
    theme_cowplot()+
    scale_color_brewer(palette = "Set1")+
    facet_grid(Strain~.)+
    scale_shape_manual(values = c(1, 3))+
    panel_border() +
    coord_flip()+
    theme(plot.title = element_text(hjust = 0.5))}
PlotZslicePa()
PlotZsliceSa()

sliceDataClean$Strain <- factor(sliceDataClean$Strain, levels = c("Sa","wt","pqsL","phz"),labels = c("Sa", "wild-type", paste0(bquote(Delta),"pqsL"), expression(paste(alpha,"phz"))))
PlotZsliceBth<-function(){  
  ggplot()+
    geom_smooth(data = sliceDataClean %>% filter(Culture=="co"),aes(y=NormBiomass,x=Height, color = Species ),size=2, alpha = .1)+
    #geom_point(data = sliceDataClean%>% filter(Species == species),aes(y=NormBiomass,x=Height, color = Region),size=1, alpha = .5)+
    geom_hline(yintercept = 0, linetype = "dashed", color = "gray")+
    theme_cowplot()+
    scale_color_brewer(palette = "Set1",breaks=c("P. aeruginosa","S. aureus"), 
                   labels = c(bquote(paste(italic("P. aeruginosa"))), bquote(paste(italic("S. aureus")))))+
    labs(color ="", y = "Percent Biomass", x = bquote(paste("Height (", mu*"m)")))+
    facet_grid(Strain~Region)+
    scale_shape_manual(values = c(1, 3))+
    panel_border() +
    coord_flip()+
    theme(plot.title = element_text(hjust = 0.5),strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}
labels = c(bquote(paste(italic("P. aeruginosa"), " wt")), bquote(paste(italic(Delta*"pqsL"))))
paste0("(1000, ",bquote("\U221E"), ")")
PlotZsliceBth()


```

```{r Metadata info}
#How many samples have been binarized?
GetTiffNum<-function(sampleName){
  parentFolder<- '/Volumes/raw_data/Confocal/Carolyn/2020/Chronic wounds/Binary Images/'
  sampleFolder<-paste0(parentFolder, sampleName)
  attrList<-str_split(sampleName,"_")[[1]]
  fileList<-list.files(path = sampleFolder, full.names = TRUE)
  tiffSlices<-(length(fileList))/3
  results<-as.data.frame(list(sampleName, attrList[1],attrList[2],attrList[3], tiffSlices))
  colnames(results)<- c("SampleCode","Condition", "TimePoint","Replicate","TiffSlices")
  results$SampleCode<-as.factor(results$SampleCode)
  return(results)
}
tiffNum<-map(metaData.df$SampleCode, GetTiffNum)
tiffNum<-bind_rows(tiffNum)
totalVoxels2<-metaData.df %>%  merge(tiffNum, by = "SampleCode") %>% mutate(SizeVoxels = xySize*xySize*TiffSlices)

sortedMetaData<-tiffNum %>% filter(TiffSlices==0)%>% select(SampleCode)
sortedMetaData[order(sortedMetaData),]

tiffStacksNew<-map(metaData.df$SampleCode, GetTiffNum)
tiffStacksNew<-bind_rows(tiffStacksNew)
tiffStacksNew %>% filter(TiffSlices==0) %>% select(SampleCode)

#How big are each of the image in bits?
totalVoxels<-sliceDataMeta %>% group_by(SampleCode, Condition, Replicate, TimePoint,xySize) %>% summarise(MaxSlice = max(Slice)) %>% ungroup() %>% mutate(ImageVoxels = MaxSlice*xySize)
```

```{r fancy histogram of aggregates !!!deprecated}
FancyHistogram<-function(df, sec){#my own way of doing histograms which includes the sum and mean of values whitin each bin
  results<-data.frame()
  for( i in 1:(length(sec)-1)){ 
    blah<-df %>% filter(Size > sec[i] &Size<=sec[i+1])%>%summarise(frequency = n(), avg = mean(Size),suma = sum(Size)) %>% mutate(bin = i, min = sec[i],max = sec[i+1])
    if(blah$frequency>0){ 
      results<-rbind(results, blah)} 
  }
  return(results) 
}
TotalFancyHistogram<-function(df,binsize){
  totalbiomass<-sum(df$Size)#total biomass per sample
  totalfrequency<-length(df$Size)#total number of objects
  upperLim<-max(df$Size)+binsize-(max(df$Size)%%binsize)#largest bin size based in largest object
  breaksSequence<-seq(0,upperLim,binsize)#this makes breaks every "binsize" 
  histogram<-FancyHistogram(df,breaksSequence)#apply "fancy histogram" to get distributions
  histogram%>%mutate(BiomassBin=suma/totalbiomass)->histogram#add column with proportion of biomass per bin
  histogram%>%mutate(Density=frequency/totalfrequency)->histogram#add column with proportion of counts per bin
  histogram%>%mutate(Species=df$Species[1])->histogram#add column maintaining sample and so on...
  histogram%>%mutate(Condition=df$Condition[1])->histogram
  histogram%>%mutate(TimePoint=df$TimePoint[1])->histogram
  histogram%>%mutate(Sample=df$Sample[1])->histogram
  return(histogram)
}

#Create histograms
##this takes a long time, so consider running them in parts
allDataGrouped<-aggregateList %>% group_by(Species, TimePoint, Condition)#first do the correct grouping
#allDataGrouped<-aggregateList %>% group_by(Species, TimePoint, Condition, Sample)# this is to include sample on the distribution or keep it out
allDataList<- group_split(allDataGrouped)#create list of dataframes
allDataHistograms.5<-map2(allDataList, 5,TotalFancyHistogram)#apply histogram function to all items in the list
allDataHistograms.5df<- bind_rows(allDataHistograms.5)#bring them together

#plotting histogram data
hist.5.LogBinSummarize<-allDataHistograms.5df %>% 
  filter(!max == 5)%>% #remove planktonic cells, but this changes the nortmalization of aggregate counts, so the normalization needs to be done later for aggs only
  group_by(Species,Condition,TimePoint)%>% mutate(LogBin = case_when(max <= 10 ~ 10,
                        max<= 100    ~ 100,
                        max<= 1000   ~ 1000,
                        max<= 10000  ~ 10000,
                        max<= 100000 ~ 100000,
                        max > 100000 ~ 1000000)) %>% ungroup() %>% 
  group_by(Species, Condition,TimePoint,LogBin) %>% summarise(FrequencyLogBin = sum(frequency), BiomassLogBin = sum(BiomassBin), DensityLogBin = sum(Density))

#plot frequency  
ggplot()+
    geom_point(data = hist.5.LogBinSummarize,aes(x=as.factor(LogBin),y=FrequencyLogBin,  color =Species ),size=4)+
    #labs(title = titulo)+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    facet_grid(.~TimePoint)+
    labs(y = "Frequency",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    #guides(color = FALSE)+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5))
  
  ggplot()+
    geom_point(data = hist.5.LogBinSummarize,aes(x=as.factor(LogBin),y=BiomassLogBin,  color =Species ),size=4)+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    facet_grid(.~TimePoint)+
    labs(y = "Biomass fraction per bin",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5))
  
  ggplot()+
    geom_point(data = hist.5.LogBinSummarize,aes(x=as.factor(LogBin),y=DensityLogBin,  color =Species ),size=4)+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    facet_grid(.~TimePoint)+
    labs(y = "Biomass fraction per bin",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5))
  

#Separating aggregates vs planktonic
hist.plank.Agg.Sumary<-allDataHistograms.5df %>%  mutate(Aggregation = case_when(max == 5 ~ "Planktonic",max>5 ~ "Aggregate")) %>%
  ungroup() %>%group_by(Species, TimePoint, Condition,Aggregation) %>% 
  summarize(FrequencyAggregation = sum(frequency), BiomassAggregation = sum(BiomassBin), DensityAggregation = sum(Density))

hist.plank.Agg.Stats<-hist.plank.Agg.Sumary %>% group_by(Species,TimePoint, Condition,Aggregation) %>%
  summarise(MeanFreq = mean(FrequencyAggregation), SEFreq = std.error(FrequencyAggregation), MeanBiomass = mean(BiomassAggregation),
            SEBiomass = std.error(BiomassAggregation),MeanDensity = mean(DensityAggregation), SEDensity = std.error(DensityAggregation))

#Plotting these guys
PlotAggsPlank<- function(){
  ggplot()+
    geom_col(data = hist.plank.Agg.Stats,aes(x=TimePoint,y=MeanBiomass, fill = Aggregation),size=3,position = position_dodge( width = .9))+
    geom_errorbar(data = hist.plank.Agg.Stats,aes(x=TimePoint,ymin=MeanBiomass-SEBiomass, ymax = MeanBiomass+SEBiomass),size=.5,position = position_dodge2( width = .6))+
    facet_grid(.~Species)+
    labs(title = "Chronic Wounds", x = "", y = "Biomass contribution")+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5))
}
PlotAggsPlank()
```

```{r Test color palettes}
library(RColorBrewer)
brewer.pal(n = 4, name = 'Set1')
```
