---
title: "SaPaFigures"
author: "Juan P Barraza"
date: "1/14/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(pixmap)
library(reshape2)
library(gplots)
library(gdata)
library(plyr)
library(dplyr)
library(ggplot2)
library(cowplot)
library(tidyr)
library(purrr)
library(plotrix)
library(ggsignif)
library(rdist)
library(stringr)

```

```{r figure 1 and 3}
#Figure 1A CFU data wt
#####
#CFU data from Carolyn
CFUdata<-read.csv("/Users/jupabago/Documents/Whiteley/PROJECTS/SaPa Chronic Wounds/Data/From Carolyn/CFU_wound_All_dataTidy.csv",header = TRUE)
CFUdata$Condition<-as.factor(CFUdata$Condition)
   CFUdata$Day<-as.factor(CFUdata$Day)
   CFUdata$Species<-as.factor(CFUdata$Species)
   CFUdata$Strain<-as.factor(CFUdata$Strain)
CFUdata$Condition <- factor(CFUdata$Condition, levels = c("mono", "co-wt", "co-pqsL"))
CFUstats<-CFUdata%>%group_by(Species,Condition,Strain,Day) %>% mutate(MeanCFU = mean(CFU), SECFU = std.error(CFU))
CFUstats$Condition <- factor(CFUstats$Condition, levels = c("mono", "co-wt", "co-pqsL"))

PlotCFUs<- function(){
ggplot()+
  geom_col(data = CFUstats %>% filter(Day == "4", Condition %in% c("mono", "co-wt"), Strain == "wt"),aes(x=Species,y=MeanCFU, fill = Condition),
           size=3,position = position_dodge( width = .9))+
  
  geom_errorbar(data = CFUstats %>% filter(Day == "4", Condition %in% c("mono", "co-wt"), Strain == "wt"),
                aes(x=Species,ymin=(MeanCFU-SECFU), ymax = (MeanCFU+SECFU), group = Condition),width = 0, size=.5,position = position_dodge(width = .9))+
  
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),expand = expand_scale(mult = c(0, 0)))+
  #facet_grid(.~Species)+
  scale_fill_grey(labels = c("Mono-culture","Co-culture"))+
  #labs(x = "", y = expression(paste(Log[10], " CFU")), linetype = "")+
    labs(x = "", y = "CFU per wound")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
        strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
        axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(face = "italic",margin = margin(1,0,0,0),size=13),
        axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}
figure1A<-PlotCFUs()
figure1A

CFUdataWT<-CFUdata %>% filter(Day == "4", Condition %in% c("mono", "co-wt"), Strain == "wt")

PlotCFUs2<- function(){
  ggplot()+
    geom_jitter(data = CFUdata %>% filter(Day == "4", Condition %in% c("mono", "co-wt"), Strain == "wt"),
                aes(x=Species,y=CFU, color = Condition),size=3,position = position_jitterdodge(jitter.height = 0,jitter.width = 0.6, dodge.width = .9))+
    geom_errorbar(data = CFUstats %>% filter(Day == "4", Condition %in% c("mono", "co-wt"), Strain == "wt"),
                aes(x=Species,ymin=(MeanCFU), ymax = (MeanCFU), group = Condition),width = .4,position = position_dodge(width = .9))+
    scale_color_grey(labels = c("Mono-culture","Co-culture"))+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),expand = expand_scale(mult = c(0, 0)), limits = c(1,10^11))+
  #labs(x = "", y = expression(paste(Log[10], " CFU")), linetype = "")+
    labs(x = "", y = "CFU per wound")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
        strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
        axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(face = "italic",margin = margin(1,0,0,0),size=13),
        axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}  
figure1A2<-PlotCFUs2()
figure1A2

#####

#Figure 1B
#####
#I am taking this code from Aggregate counts.RMD, but the biomass is lower case on the df that I have
BiomassData<-aggregateList%>% group_by(SampleCode,Species,SaStrain,Strain,Culture,TimePoint,Condition,Replicate,Region) %>% 
  summarise(Aggs = n(), Biomass = sum(Size), MeanAggSize = mean(Size), SEAggSize = std.error(Size), MaxSize = max(Size), MinSize = min(Size)) %>%
  ungroup() %>% mutate(RatioMaxTotal = MaxSize/Biomass) 

BiomassDataStats<-BiomassData %>% 
  group_by(Species,SaStrain,Strain,Culture,TimePoint,Condition) %>% 
  summarise(MeanAggs= mean(Aggs),MeanBiomass = mean(Biomass), SEBiomass = std.error(Biomass), MeanBiomassLog = mean(log10(Biomass)), SEBiomassLog = std.error((log10(Biomass))), MeanMeanAggSize = mean(MeanAggSize), SEMeanAggSize = std.error(MeanAggSize))

BiomassDataWt = BiomassData%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono") %>% filter(TimePoint == "Day 4" )
BiomassDataMut = BiomassData %>% filter(TimePoint == "Day 4" )
biomassWTData = BiomassDataStats%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono") %>% filter(TimePoint == "Day 4" )
biomassMutData = BiomassDataStats  %>% filter(TimePoint == "Day 4" )

#Carolyn wanted to play with the data so here it is:
write.csv(BiomassDataWt,"/Users/jpb/Library/Mobile Documents/com~apple~CloudDocs/Documents/Whiteley/PROJECTS/SaPa Chronic Wounds/Data/CSV exports/BiomassWT.csv", row.names = T)
write.csv(BiomassDataMut,"/Users/jpb/Library/Mobile Documents/com~apple~CloudDocs/Documents/Whiteley/PROJECTS/SaPa Chronic Wounds/Data/CSV exports/BiomassMut.csv", row.names = T)
write.csv(biomassMutData,"/Users/jpb/Library/Mobile Documents/com~apple~CloudDocs/Documents/Whiteley/PROJECTS/SaPa Chronic Wounds/Data/CSV exports/BiomassMutStats.csv", row.names = T)

write.csv(HistReplicateSummary,"/Users/jpb/Library/Mobile Documents/com~apple~CloudDocs/Documents/Whiteley/PROJECTS/SaPa Chronic Wounds/Data/CSV exports/ReplicateData.csv", row.names = T)
write.csv(HistConditionSummary,"/Users/jpb/Library/Mobile Documents/com~apple~CloudDocs/Documents/Whiteley/PROJECTS/SaPa Chronic Wounds/Data/CSV exports/ConditionData.csv", row.names = T)
write.csv(HistCondRegionSum,"/Users/jpb/Library/Mobile Documents/com~apple~CloudDocs/Documents/Whiteley/PROJECTS/SaPa Chronic Wounds/Data/CSV exports/RegionData.csv", row.names = T)


PlotBiomass<- function(){
  ggplot()+
    geom_col(data = biomassWTData,aes(x=Species,y=MeanBiomass, fill = Culture),
             size=3,position = position_dodge( width = .9))+
    geom_errorbar(data = biomassWTData, aes(x=Species,ymin=(MeanBiomass-SEBiomass), ymax = (MeanBiomass+SEBiomass), group = Culture)
                ,width = 0, size=.5,position = position_dodge(width = .9))+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),expand = expand_scale(mult = c(0, 0)))+
    scale_fill_grey(labels = c("Mono-culture","Co-culture"))+
    labs(x = "",y = bquote(paste("Biomass per image (", mu*"m"^3*")")))+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
          axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(face = "italic",margin = margin(1,0,0,0),size=13),
          axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}

figure1B<-PlotBiomass()
figure1B

PlotBiomassPoints<- function(){
  ggplot()+
    geom_jitter(data = BiomassDataWt,aes(x=Species,y=Biomass, color = Culture),size=3,position = position_jitterdodge(jitter.height = 0,jitter.width = 0.2, dodge.width = .9))+
    geom_errorbar(data = biomassWTData, aes(x=Species,ymin=(MeanBiomass), ymax = (MeanBiomass), group = Culture)
                ,width = .4, size=.5,position = position_dodge(width = .9))+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),
                  limits = c(100, 10e7), expand = expand_scale(mult = c(0, 0)))+
    scale_color_grey(labels = c("Mono-culture","Co-culture"))+
    labs(x = "",y = bquote(paste("Biomass per image (", mu*"m"^3*")")))+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
          axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(face = "italic",margin = margin(1,0,0,0),size=13),
          axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}
PlotBiomassPoints()

PlotBiomassPointsMutants<- function(){
  ggplot()+
    geom_jitter(data = BiomassDataMut,aes(x=Species,y=Biomass, color = Strain),size=3,position = position_jitterdodge(jitter.height = 0,jitter.width = 0.2, dodge.width = .9))+
    geom_errorbar(data = biomassMutData, aes(x=Species,ymin=(MeanBiomass), ymax = (MeanBiomass), group = Strain)
                ,width = .4, size=.5,position = position_dodge(width = .9))+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),
                  limits = c(1, 10e7), expand = expand_scale(mult = c(0, 0)))+
    scale_color_manual(values=c("#000000", "#3964C3", "#D34328"),
      labels = c(bquote(paste(italic('S. aureus + P. aeruginosa '))),
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"pqsL"))), 
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"phz")))))+
    
    labs(x = "",y = bquote(paste("Biomass per image (", mu*"m"^3*")")), color = "Condition")+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
          axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(face = "italic",margin = margin(1,0,0,0),size=13),
          axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}
PlotBiomassPointsMutantsViolin<- function(){
  ggplot()+
    geom_violin(data = BiomassDataMut,aes(x=Species,y=Biomass, color = Strain))+
    geom_errorbar(data = biomassMutData, aes(x=Species,ymin=(MeanBiomass), ymax = (MeanBiomass), group = Strain)
                ,width = .4, size=.5,position = position_dodge(width = .9))+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),
                  limits = c(1, 10e7), expand = expand_scale(mult = c(0, 0)))+
    scale_color_brewer(palette = "Set1",
      labels = c(bquote(paste(italic('S. aureus + P. aeruginosa '))),
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"pqsL"))), 
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"phz")))))+
    
    labs(x = "",y = bquote(paste("Biomass per image (", mu*"m"^3*")")), color = "Condition")+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
          axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(face = "italic",margin = margin(1,0,0,0),size=13),
          axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}
PlotBiomassPointsMutants()
PlotBiomassPointsMutantsViolin()
#####

```
#####

```{r figure 2 Core vs Edge}

#Figure 2B: Percent CFU inner wound
##### 
CFUInOutData<-read.csv("/Users/jupabago/Documents/Whiteley/PROJECTS/SaPa Chronic Wounds/Data/From Carolyn/Inside_Outside_CFUcm2_Day4Tidy.csv",header = TRUE)
CFUInOutData<-Filter(function(x)!all(is.na(x)), CFUInOutData)#this is to remove columns with NA
CFUInOutData <- na.omit(CFUInOutData) #removing rows with NA
CFUInOutData$Condition<-as.factor(CFUInOutData$Condition)
CFUInOutData$Sample<-as.factor(CFUInOutData$Sample)
CFUInOutData$Species<-as.factor(CFUInOutData$Species)
CFUInOutData$Strain<-as.factor(CFUInOutData$Strain)

CFUInOutDataPost<-CFUInOutData %>% mutate(CFU.Inside = Inside.Bandage+Inside.Tissue, CFU.Outside = Outside.Tissue+Outside.Bandage) %>% mutate(PercentIn = 100*CFU.Inside/(CFU.Inside+CFU.Outside))

CFUInOutStats<-CFUInOutDataPost%>% group_by(Species,Strain,Condition) %>% summarise(meanInPercent = mean(PercentIn), SEInPercent = std.error(PercentIn))
CFUInOutStatsWt<-CFUInOutStats %>% filter(!Condition=="co-pqsL") %>% filter(Strain == "wt")
CFUInOutStatsWt$Condition <- factor(CFUInOutStatsWt$Condition, levels = c("mono", "co-wt"))

PlotInCFUs<- function(){
  ggplot()+
    geom_col(data = CFUInOutStatsWt,aes(x=Species,y=meanInPercent, fill = Condition),size=3,position = position_dodge( width = .9))+
    geom_errorbar(data = CFUInOutStatsWt,aes(x=Species,ymin=(meanInPercent-SEInPercent), ymax = (meanInPercent+SEInPercent), group = Condition),width = 0, size=.5,position = position_dodge(width = .9))+
    scale_fill_grey(labels = c("Mono-culture","Co-culture"))+
    scale_y_continuous(expand = expand_scale(mult = c(0, 0)))+
  #labs(x = "", y = expression(paste(Log[10], " CFU")), linetype = "")+
    labs(x = "",y = bquote(paste("% CFU/", "cm"^2*" in wound core")))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
        strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
        axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(face = "italic",margin = margin(1,0,0,0),size=13),
        axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
  }
figure2A<-PlotInCFUs()
figure2A

#now with geom_point
CFUInOutPostWt<-CFUInOutDataPost %>% filter(!Condition=="co-pqsL") %>% filter(Strain == "wt")
CFUInOutPostWt$Condition <- factor(CFUInOutPostWt$Condition, levels = c("mono", "co-wt"))

PlotInCFUs2<- function(){
  ggplot()+
    geom_jitter(data = CFUInOutPostWt,aes(x=Species,y=PercentIn, color = Condition),size=3,position = position_jitterdodge(jitter.height = 0,jitter.width = 0.2, dodge.width = .9))+
    geom_errorbar(data = CFUInOutStatsWt,aes(x=Species,ymin=(meanInPercent), ymax = (meanInPercent), group = Condition),width = .4, size=.5,position = position_dodge(width = .9))+
    scale_color_grey(labels = c("Mono-culture","Co-culture"))+
    scale_y_continuous(expand = expand_scale(mult = c(0, 0)), limits = c(0,100))+
  #labs(x = "", y = expression(paste(Log[10], " CFU")), linetype = "")+
    labs(x = "",y = bquote(paste("% CFU/", "cm"^2*" in healing edge")))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
        strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
        axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(face = "italic",margin = margin(1,0,0,0),size=13),
        axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}  
figure2A2<-PlotInCFUs2()
figure2A2

#With the mutants

#####
#Figure 2C
#####
#this is taken from AggregateCounts.Rmd section Plot Aggregagte size bins

PlotHistSumFinal<-function(rep.df,cond.df,region.df, y_var, colorStrain){
ggplot()+
    geom_point(data = rep.df %>% filter(TimePoint=="Day 4"),
                aes(x=as.factor(LogBin),y=.data[[y_var]], color =.data[[colorStrain]], shape = Region),
               position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75),size=1)+
    geom_point(data = region.df%>% filter(TimePoint=="Day 4"),
               aes(x=as.factor(LogBin),y=.data[[y_var]], color =.data[[colorStrain]],shape = Region),
               size=3, position = position_dodge(width = .75) )+
    geom_errorbar(data = cond.df%>% filter(TimePoint=="Day 4"),
               aes(x=as.factor(LogBin),ymin=.data[[y_var]],ymax=.data[[y_var]], group =.data[[colorStrain]]),width = .5,position = position_dodge(width = .75) )+
    facet_grid(.~Species)+
    scale_shape_manual(values=c(16, 1))+
    scale_color_grey(labels = c("Mono-culture","Co-culture"))+
    scale_x_discrete(labels = c("Planktonic", "5-10", "10-100", "100-1000", ">1000"))+
    labs(y = paste("Frequency (%)"),x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    theme_cowplot()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}

PlotHistSumFinal(HistReplicateSummary%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
            HistConditionSummary%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
            HistCondRegionSum%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
            "NormalizedFrequency", "Culture")

PlotHistSumFinalViolin<-function(rep.df,cond.df,region.df, y_var, colorStrain){
ggplot()+
    geom_violin(data = rep.df %>% filter(TimePoint=="Day 4"),
                scale = "width", trim = T, position = position_dodge(width = .85) ,
                aes(x=as.factor(LogBin),y=.data[[y_var]], linetype =.data[[colorStrain]]))+
    geom_point(data = region.df%>% filter(TimePoint=="Day 4"),
               aes(x=as.factor(LogBin),y=.data[[y_var]], group =.data[[colorStrain]],shape = CultureRegion),
               size=3, position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = .75))+
    geom_errorbar(data = cond.df%>% filter(TimePoint=="Day 4"),
               aes(x=as.factor(LogBin),ymin=.data[[y_var]],ymax=.data[[y_var]], group =.data[[colorStrain]]),width = .6,position = position_dodge(width = .75) )+
    facet_grid(.~Species)+
    scale_shape_manual(values=c( 16,17,1,2))+
    scale_linetype_manual(values=c( "dashed","solid"),labels = c("Mono-infection","Co-infection"))+
    scale_x_discrete(labels = c("Planktonic", "5-10", "10-100", "100-1000", ">1000"))+
    labs(y = paste("Frequency (%)"),x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    theme_cowplot()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}

PlotHistSumFinalViolin(HistReplicateSummary%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
            HistConditionSummary%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
            HistCondRegionSum%>% filter(Condition == "Sa mono" |Condition == "wt co"|Condition == "wt mono"),
            "NormalizedFrequency", "Culture")
HistCondRegionSum = HistCondRegionSum %>% unite(CultureRegion, Culture, Region, sep = " ", remove = FALSE)

#only difference between these two should be "scale_color_grey"
PlotHistSumFinalStrains<-function(rep.df,cond.df,region.df, y_var, colorStrain){
ggplot()+
    geom_point(data = rep.df %>% filter(TimePoint=="Day 4"),
                aes(x=as.factor(LogBin),y=.data[[y_var]], color =.data[[colorStrain]], shape = Region),
               position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 1),size=2)+
    geom_point(data = region.df%>% filter(TimePoint=="Day 4"),
               aes(x=as.factor(LogBin),y=.data[[y_var]], color =.data[[colorStrain]],shape = Region),
               size=5, position = position_dodge(width = 1) )+
    geom_errorbar(data = cond.df%>% filter(TimePoint=="Day 4"),
               aes(x=as.factor(LogBin),ymin=.data[[y_var]],ymax=.data[[y_var]], group =.data[[colorStrain]]),width = .8,position = position_dodge(width = 1) )+
    facet_grid(.~Species)+
    scale_shape_manual(values=c(16, 1))+
    scale_color_grey(labels = c(bquote(paste(italic('S. aureus + P. aeruginosa '))),
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"pqsL"))), 
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"phz")))))+
    scale_x_discrete(labels = c("Planktonic", "5-10", "10-100", "100-1000", ">1000"))+
    labs(y = paste("Frequency (%)"),x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")), color = "Condition")+
    theme_cowplot()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}#only difference between these two should be "scale_color_grey
PlotHistSumFinalStrains(HistReplicateSummary%>% filter(Culture =="co"),
            HistConditionSummary%>% filter(Culture =="co"),
            HistCondRegionSum%>% filter(Culture =="co"),
            "NormalizedFrequency","Strain")

PlotHistSumFinalStrainsViolin<-function(rep.df,cond.df,region.df, y_var, colorStrain){#doesn't include region
ggplot()+
    geom_violin(data = rep.df %>% filter(TimePoint=="Day 4"),
                scale = "width", trim = T,
                aes(x=as.factor(LogBin),y=.data[[y_var]], color =.data[[colorStrain]]))+
    geom_point(data = region.df%>% filter(TimePoint=="Day 4"),
               aes(x=as.factor(LogBin),y=.data[[y_var]], color =.data[[colorStrain]],shape = Region),
               size=5, position = position_dodge(width = 1) )+
    geom_errorbar(data = cond.df%>% filter(TimePoint=="Day 4"),
               aes(x=as.factor(LogBin),ymin=.data[[y_var]],ymax=.data[[y_var]], group =.data[[colorStrain]]),width = .8,position = position_dodge(width = 1) )+
    facet_grid(.~Species)+
    scale_shape_manual(values=c(16, 1))+
    scale_color_manual(values=c("#000000", "#3964C3", "#D34328"),
                       labels = c(bquote(paste(italic('S. aureus + P. aeruginosa '))),
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"pqsL"))), 
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"phz")))))+
    scale_x_discrete(labels = c("Planktonic", "5-10", "10-100", "100-1000", ">1000"))+
    labs(y = paste("Frequency (%)"),x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")), color = "Condition")+
    theme_cowplot()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}#only difference between these two should be "scale_color_grey
PlotHistSumFinalStrainsViolin(HistReplicateSummary%>% filter(Culture =="co"),
            HistConditionSummary%>% filter(Culture =="co"),
            HistCondRegionSum%>% filter(Culture =="co"),
            "NormalizedFrequency","Strain")

#####
#Figure 2D
#Aggregation inner vs outer region
#####
PlotAggCore<-function(rep.df,region.df, y_var, title,colorStrain, facet){
ggplot()+
    geom_point(data = rep.df %>% filter(TimePoint=="Day 4"),
                aes(x=.data[[colorStrain]],y=.data[[y_var]], shape = Region, color =.data[[colorStrain]]),
               position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75),size=3, show.legend = F)+
    geom_errorbar(data = region.df%>% filter(TimePoint=="Day 4"),
               aes(x=.data[[colorStrain]],ymin=.data[[y_var]],ymax=.data[[y_var]], group =Region),
               size=.5,width = 0.5, position = position_dodge(width = .75) )+
    #geom_point(data = cond.df%>% filter(TimePoint=="Day 4"),
     #          aes(x=Region,y=.data[[y_var]],  color =.data[[colorStrain]]),size=4, shape = 3,position = position_dodge(width = .75) )+
    scale_y_log10(breaks = c(100, 10, 1, .1, .01), labels = c(100, 10, 1, .1, .01))+
    facet_grid(.~.data[[facet]])+
    scale_shape_manual(values=c(16, 1))+
    scale_color_grey(labels = c("Mono-culture","Co-culture"))+
    scale_x_discrete(labels = c("Mono-culture","Co-culture"))+
    ggtitle(title)+
    labs(y = paste("Planktonic Biomass Contribution (%)"), x = "")+
    theme_cowplot()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}

PlotAggCore(plankAggHistRep%>% filter(Strain %in% c("Sa", "wt")) %>% filter(Aggregation=="Planktonic"),
             plankAggHistCondReg%>% filter(Strain %in% c("Sa", "wt"))%>% filter(Aggregation=="Planktonic"),
             "AgPlNormBiomass", "", "Culture", "Species")

# Violin Plots
## 2 versions, one with the species as a facet and the other one with species as x-axis
### Mono vs co
#####
plankAggHistCondReg= plankAggHistCondReg %>% unite(CultureRegion, Culture, Region, sep = " ", remove = FALSE)#this is for the shapes fill and triangle vs circle

PlotAggCoreViolinFacet<-function(rep.df,region.df, cond.df,y_var,colorStrain, facet){
ggplot()+
    geom_violin(data = rep.df %>% filter(TimePoint=="Day 4"),
                aes(x=.data[[colorStrain]],y=.data[[y_var]], linetype =.data[[colorStrain]]),
               position = position_dodge(width = 0.75),show.legend = T)+
    geom_errorbar(data =cond.df %>% filter(TimePoint=="Day 4"),
               aes(x=.data[[colorStrain]],ymin=.data[[y_var]],ymax=.data[[y_var]]),
               size=.5,width = 0.5, position = position_dodge(width = .75) )+
    geom_point(data = region.df%>% filter(TimePoint=="Day 4"),
               aes(x=.data[[colorStrain]],y=.data[[y_var]],  shape =CultureRegion),size=4, position = position_dodge(width = .75) )+
    scale_y_log10(breaks = c(100, 10, 1, .1, .01), labels = c(100, 10, 1, .1, .01))+
    facet_grid(.~.data[[facet]])+
    scale_shape_manual(values=c( 16,17,1,2))+
    #scale_color_grey(labels = c("Mono-culture","Co-culture"))+
    scale_x_discrete(labels = c("Mono-infection","Co-infection"))+
    scale_linetype_manual(values=c( "dashed","solid"),labels = c("Mono-infection","Co-infection"))+
    labs(y = paste("Planktonic Biomass Contribution (%)"), x = "")+
    theme_cowplot()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}
PlotAggCoreViolinFacet(plankAggHistRep%>% filter(Strain %in% c("Sa", "wt")) %>% filter(Aggregation=="Planktonic"),
             plankAggHistCondReg%>% filter(Strain %in% c("Sa", "wt"))%>% filter(Aggregation=="Planktonic"),
             plankAggHistCond%>% filter(Strain %in% c("Sa", "wt"))%>% filter(Aggregation=="Planktonic"),
             "AgPlNormBiomass", "Culture", "Species")

PlotAggCoreViolin<-function(rep.df,region.df, cond.df,y_var,colorStrain, facet){
ggplot()+
    geom_violin(data = rep.df %>% filter(TimePoint=="Day 4"),
                aes(x=.data[[facet]],y=.data[[y_var]], linetype =.data[[colorStrain]]),
               position = position_dodge(width = 0.75),show.legend = T)+
    geom_errorbar(data =cond.df %>% filter(TimePoint=="Day 4"),
               aes(x=.data[[facet]],ymin=.data[[y_var]],ymax=.data[[y_var]], group = Culture),
               size=.5,width = 0.5, position = position_dodge(width = .75) )+
    geom_point(data = region.df%>% filter(TimePoint=="Day 4"),
               aes(x=.data[[facet]],y=.data[[y_var]],  group= Culture, shape =CultureRegion),size=4, 
               position = position_jitterdodge(jitter.height = 0, jitter.width = .2,dodge.width = .75) )+
    scale_y_log10(breaks = c(100, 10, 1, .1, .01), labels = c(100, 10, 1, .1, .01))+
    #facet_grid(.~.data[[facet]])+
    scale_shape_manual(values=c( 16,17,1,2))+
    #scale_color_grey(labels = c("Mono-infection","Co-culture"))+
    scale_x_discrete(labels = c(bquote(italic('P. aeruginosa')),bquote(italic('S. aureus'))))+
    scale_linetype_manual(values=c( "dashed","solid"),labels = c("Mono-infection","Co-infection"))+
    labs(y = paste("Planktonic Biomass Contribution (%)"), x = "")+
    theme_cowplot()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}
PlotAggCoreViolin(plankAggHistRep%>% filter(Strain %in% c("Sa", "wt")) %>% filter(Aggregation=="Planktonic"),
             plankAggHistCondReg%>% filter(Strain %in% c("Sa", "wt"))%>% filter(Aggregation=="Planktonic"),
             plankAggHistCond%>% filter(Strain %in% c("Sa", "wt"))%>% filter(Aggregation=="Planktonic"),
             "AgPlNormBiomass", "Culture", "Species")
#####
### Mutants
PlotAggCoreMut<-function(rep.df,region.df, y_var, title,colorStrain, facet){
ggplot()+
    geom_point(data = rep.df %>% filter(TimePoint=="Day 4"),
                aes(x=Region,y=.data[[y_var]], shape = Region, color =.data[[colorStrain]]),
               position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75),size=3)+
    geom_errorbar(data = region.df%>% filter(TimePoint=="Day 4"),
               aes(x=Region,ymin=.data[[y_var]],ymax=.data[[y_var]], group =Strain),
               size=.5,width = 0.5, position = position_dodge(width = .75) )+
    #geom_point(data = cond.df%>% filter(TimePoint=="Day 4"),
     #          aes(x=Region,y=.data[[y_var]],  color =.data[[colorStrain]]),size=4, shape = 3,position = position_dodge(width = .75) )+
    scale_y_log10(breaks = c(100, 10, 1, .1, .01), labels = c(100, 10, 1, .1, .01))+
    facet_grid(.~.data[[facet]])+
    scale_shape_manual(values=c(16, 1))+
    scale_color_manual(values=c("#000000", "#3964C3", "#D34328"),
                       labels = c(bquote(paste(italic('S. aureus + P. aeruginosa '))),
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"pqsL"))), 
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"phz")))))+
    ggtitle(title)+
    labs(y = paste("Planktonic Biomass Contribution (%)"), x = "")+
    theme_cowplot()+
    panel_border() +
    theme(plot.title = element_text(hjust = 0.5), 
        strip.text = element_text(size = 11, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facet text
        strip.background = element_rect(color="black", fill="white", size=1, linetype="solid"))#facet background
}

PlotAggCoreMut(plankAggHistRep%>% filter(Culture=="co") %>% filter(Aggregation=="Planktonic"),
             plankAggHistCondReg%>% filter(Culture=="co")%>% filter(Aggregation=="Planktonic"),
             plankAggHistCond%>% filter(Culture=="co")%>% filter(Aggregation=="Planktonic"),
             "AgPlNormBiomass", "", "Strain", "Species")


#####

#Figure 2E
## Enrichment distance
#####
##Marvin suggested doing the enrichment distance for those samples, but I guess there is nothing to compare, unless I do core vs edge
##ggplot code from PropOc Data 3D
## sending these to Carolyn for plotting

write.csv(pOEnrMetaClean %>% filter(Relation == "Pa->Sa", TimePoint=="Day 4"),"/Users/jpb/Library/Mobile Documents/com~apple~CloudDocs/Documents/Whiteley/PROJECTS/SaPa Chronic Wounds/Data/CSV exports/EDData.csv", row.names = T)
write.csv(pOEnrMetaStatsRegion %>% filter(Relation == "Pa->Sa", TimePoint=="Day 4"),"/Users/jpb/Library/Mobile Documents/com~apple~CloudDocs/Documents/Whiteley/PROJECTS/SaPa Chronic Wounds/Data/CSV exports/EDStats.csv", row.names = T)


PlotwtED<-function(){
df1<-pOEnrMetaStatsRegion %>% filter(Relation == "Pa->Sa", TimePoint=="Day 4", Condition == "wt co")
df2<-pOEnrMetaClean %>% filter(Relation == "Pa->Sa", TimePoint=="Day 4", Condition == "wt co")

  ggplot()+
    geom_errorbar(data = df1,aes(y=meanED,ymax=meanED,ymin=meanED, group = Region,x = Condition),
                    position = position_dodge(width = .75), width = 0.5)+
    geom_point(data = df2,aes(y=WmeanDist,x = Condition, shape = Region),position = position_jitterdodge(jitter.height = 0, jitter.width = .3,dodge.width = 0.75),size=3)+
    labs(y = expression(atop("Enrichment distance ("*mu*"m)",paste(italic("S. aureus") %->% italic("S. aureus ")))), x = "") +
    scale_color_grey()+
    scale_x_discrete(labels = c(""))+
    scale_shape_manual(values=c(16, 1))+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5),
          strip.text = element_text(size = 12,margin = margin(.1,0,.1,0, "cm")),#this is for the facets
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"))+
    panel_border() 
}

PlotwtED()
#In this case, i want an actual x axis, but the top may work for reference
PlotwtED2<-function(){
df1<-pOEnrMetaStatsRegion %>% filter(Relation == "Pa->Sa", TimePoint=="Day 4", Condition == "wt co")
df2<-pOEnrMetaClean %>% filter(Relation == "Pa->Sa", TimePoint=="Day 4", Condition == "wt co")
  ggplot()+
    geom_errorbar(data = df1,aes(y=meanED,ymax=meanED,ymin=meanED, x = Region), width = .5)+
    geom_point(data = df2,aes(y=WmeanDist,x = Region, shape = Region),position = position_jitter(height = 0, width = .2),size=3, show.legend = F)+
    labs(y = expression(atop("Enrichment distance ("*mu*"m)",paste(italic("S. aureus") %->% italic("S. aureus ")))), x = "") +
    scale_color_grey()+
    scale_shape_manual(values=c(16, 1))+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5),
          strip.text = element_text(size = 12,margin = margin(.1,0,.1,0, "cm")),#this is for the facets
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"))+
    panel_border() 
}

PlotwtED2()
#####
#Figure 2F
PlotEDvsDensityFinal<-function(df, yAxis,tittle){
  ggplot()+
    geom_point(data = df,aes(y=WmeanDist,x=.data[[yAxis]], color= Strain, shape =Region ),size=4)+
    #geom_smooth(data = df,aes(y=WmeanDist,x=.data[[yAxis]],color = Strain, shape =Region ),size=4)+
    geom_abline(intercept = 10.683, slope = 44.416, color = "Black")+
    #geom_text(x=.3, y=30, label= bquote(paste("R"^2*"=0.3368")))+
    #geom_text(x=.3, y=10, label= "bl")+
    annotate(geom="text", x=.3, y=10, label=bquote(paste("R"^2*"=0.3368")))+
    scale_color_manual(values=c("#000000", "#3964C3", "#D34328"),
                       labels = c(bquote(paste(italic('S. aureus + P. aeruginosa '))),
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"pqsL"))), 
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"phz")))))+
    #geom_abline(intercept = 9.011, slope = 37.488, color = "Green")+
    #geom_abline(intercept = 9.519, slope = 50.800, color = "Red")+
    labs(title =tittle, y = "Mean Enrichment Distance", x = "Bacterial Density")+
    scale_shape_manual(values=c(16, 17))+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5))
}
PlotEDvsDensityFinal(EdSlice %>% filter(Strain == "wt"), "TotalRatio","")
PlotEDvsDensityFinal2<-function(df, yAxis,tittle){
  ggplot()+
    geom_point(data = df,aes(y=WmeanDist,x=.data[[yAxis]], color= Strain, shape =Region ),size=4)+
    #geom_smooth(data = df,aes(y=WmeanDist,x=.data[[yAxis]],color = Strain, shape =Region ),size=4)+
    #geom_abline(intercept = 10.683, slope = 44.416, color = "Black")+
    #geom_text(x=.3, y=30, label= bquote(paste("R"^2*"=0.3368")))+
    #geom_text(x=.3, y=10, label= "bl")+
    #annotate(geom="text", x=.3, y=10, label=bquote(paste("R"^2*"=0.3368")))+
    scale_color_manual(values=c("#000000", "#D34328", "#3964C3"),
                       labels = c(bquote(paste(italic('S. aureus + P. aeruginosa '))),
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"pqsL"))), 
                                bquote(paste(italic('S. aureus + P. aeruginosa '*Delta*"phz")))))+
    #geom_abline(intercept = 9.011, slope = 37.488, color = "Green")+
    #geom_abline(intercept = 9.519, slope = 50.800, color = "Black")+
    labs(title =tittle, y = "Mean Enrichment Distance", x = "Bacterial Density")+
    scale_shape_manual(values=c(16, 17))+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5))
}

PlotEDvsDensityFinal2(EdSlice, "TotalRatio","")


```

```{r Figure 4}
#Antibiotic data
ReadAbData<-function(){
df<-read.csv("/Users/jupabago/Documents/Whiteley/PROJECTS/SaPa Chronic Wounds/Data/AntibioticTreatment_percentofuntreatedTidy.csv",header = TRUE)
df<-Filter(function(x)!all(is.na(x)), df)#this is to remove columns with NA
df <- na.omit(df) #removing rows with NA
df$Condition<-as.factor(df$Condition)
df$Sample<-as.factor(df$Sample)
df$Species<-as.factor(df$Species)
df$Treatment<-as.factor(df$Treatment)
df$Structure<-as.factor(df$Structure)
return(df)
}
AbData<-ReadAbData()
AbData$Condition <- factor(AbData$Condition, levels = c("mono", "co-wt", "co-pqsL"))
AbData<-AbData %>% group_by(Structure, Species, Condition, Sample) %>%  mutate(SurvivalFinal = mean(Survival)) %>% filter(!Treatment=="Treated1")
AbData<-AbData %>% mutate(SurvivalRatio = SurvivalFinal/100)
AbDataStats<-AbData %>% group_by(Species, Structure,Condition) %>% summarise(MeanSurvival = mean(SurvivalFinal), SESurvival = std.error(SurvivalFinal), 
                                                                             MeanSurRatio = mean(SurvivalRatio), SESurRatio = std.error(SurvivalRatio)) %>% ungroup()


PlotAbData<-function(df,xaxis,yaxis, error, fill){
ggplot()+
  geom_col(data = df%>% filter(Species == "S. aureus"),aes(x=.data[[xaxis]],y=.data[[yaxis]], fill = .data[[fill]]),size=3,position = position_dodge( width = .9))+
  geom_errorbar(data = df%>% filter(Species == "S. aureus"),aes(x=.data[[xaxis]],ymin=(.data[[yaxis]]-.data[[error]]), ymax = (.data[[yaxis]]+.data[[error]]), group = .data[[fill]]),
                width = 0, size=.5,position = position_dodge(width = .9))+
  scale_y_continuous(expand = expand_scale(mult = c(0, 0)))+
  #scale_y_log10(limits = c(.0001,100))+
  #facet_grid(.~Species)+
  scale_fill_grey(labels = c("Mono-culture","Co-culture wt", "Co-culture pqsL"))+
  #labs(x = "", y = expression(paste(Log[10], " CFU")), linetype = "")+
  labs(x = "", y = expression(paste(italic(S.aureus )," % Survival" )))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
        strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
        axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(face = "italic",margin = margin(1,0,0,0),size=13),
        axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}
PlotAbData(AbDataStats,"Structure","MeanSurvival","SESurvival", "Condition")

PlotAbData2<-function(){
ggplot()+
  geom_jitter(data = AbData %>% filter(Species == "S. aureus"),aes(x=Structure,y=SurvivalRatio, shape = Sample, color = Condition, group = Condition),size=3,
              position = position_jitterdodge(jitter.height = 0,jitter.width = 0.2, dodge.width = .9))+
  geom_errorbar(data = AbDataStats %>% filter(Species == "S. aureus"),aes(x=Structure,ymin=(MeanSurRatio), ymax = (MeanSurRatio), group = Condition),
                width = .5, size=.5,position = position_dodge(width = .9))+
  #facet_grid(.~Species)+
  scale_color_grey(labels = c("Mono-culture","Co-culture wt", "Co-culture pqsL"))+
  #labs(x = "", y = expression(paste(Log[10], " CFU")), linetype = "")+
    #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  labs(x = "", y = expression(paste(italic(S.aureus )," Survival fraction" )))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
        strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
        axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,0,0),size=13),
        axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}
PlotAbData2()

#This doesn't really gets the point across, so get the ratio of survival in treated vs untreated
AbData<-AbData %>% ungroup() %>% group_by(Sample, Species, Condition) %>% mutate(SurvivalRatioStructure = SurvivalRatio/SurvivalRatio[Structure=="Unstructured"],SurvivalDifferenceStructure = SurvivalFinal[Structure=="Unstructured"]-SurvivalFinal )
#now we redo AbDataStats:
AbDataUnstructureStats<-AbData %>% filter(Structure == "Structured") %>% group_by(Species, Condition) %>%
  summarise(MeanRatio = mean(SurvivalRatioStructure), SESurvival = std.error(SurvivalRatioStructure),
            MeanDifference = mean(SurvivalDifferenceStructure), SEDifference = std.error(SurvivalDifferenceStructure))%>% ungroup()

PlotAbData3<-function(df,xaxis,yaxis, error, fill){
ggplot()+
  geom_col(data = df %>% filter(Species == "S. aureus"),aes(x=.data[[xaxis]],y=.data[[yaxis]], fill = .data[[fill]]),size=3,position = position_dodge( width = .9))+
  geom_errorbar(data = df%>% filter(Species == "S. aureus"),aes(x=.data[[xaxis]],ymin=(.data[[yaxis]]-.data[[error]]), ymax = (.data[[yaxis]]+.data[[error]]), group = .data[[fill]]),
                width = 0, size=.5,position = position_dodge(width = .9))+
  scale_y_continuous(expand = expand_scale(mult = c(0, 0)))+
  #scale_y_log10(expand = expand_scale(mult = c(0, 0)))+
  #facet_grid(.~Species)+
  scale_fill_grey(labels = c("Mono-culture","Co-culture wt", "Co-culture pqsL"))+
  #labs(x = "", y = expression(paste(Log[10], " CFU")), linetype = "")+
  labs(x = "", y = "Survival fraction Structured/Unstructured")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
        strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
        axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(face = "italic",margin = margin(1,0,0,0),size=13),
        axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}
PlotAbData3(AbDataUnstructureStats,"Species","MeanRatio","SESurvival", "Condition")
PlotAbData3(AbDataUnstructureStats,"Species","MeanDifference","SEDifference", "Condition")
#now using the jittel points

PlotAbData4<-function(){
ggplot()+
  geom_jitter(data = AbData %>% filter(Species == "S. aureus") %>% filter(Structure == "Structured") ,
              aes(x=Species,y=SurvivalRatioStructure, color = Condition, group = Condition, shape = Sample),size=3,
              position = position_jitterdodge(jitter.height = 0,jitter.width = 0.2, dodge.width = .9))+
  geom_errorbar(data = AbDataUnstructureStats %>% filter(Species == "S. aureus"),
                aes(x=Species,ymin=(MeanRatio), ymax = (MeanRatio), group = Condition),
                width = .5, size=.5,position = position_dodge(width = .9))+
  #facet_grid(.~Species)+
  scale_color_grey(labels = c("Mono-culture","Co-culture wt", "Co-culture pqsL"))+
  labs(x = "", y = expression(paste(italic(S.aureus )," survival fraction Structured/Unstructured" )))+
    scale_y_log10(breaks = c(1,10,100,1000), labels = c(1,10,100,1000), limits = c(1, 10000))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
        strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
        axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,0,0),size=13),
        axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}
PlotAbData4()

```