---
title: "Proportional Occupancy"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(pixmap)
library(rtiff)
library(reshape2)
library(gplots)
library(gdata)
library(plyr)
library(dplyr)
library(ggplot2)
library(cowplot)
library(tidyr)
library(purrr)
library(plotrix)
library(ggsignif)
library(rdist)
library(EBImage)
library(tictoc)
library(stringr)
```

```{r functions to get data}
#using the new 3D script with capped spheres.
source('/home/jbarraza6/Documents/RScripts/PropOcFunctions2.0.R') #for Thor
source('/Users/jupabago/Documents/Whiteley/PROJECTS/Rpackage/PropOc Package/R/PropOcFunctions2.0.R') #for laptop

metaData.df <-read.csv('/run/user/937561/gvfs/smb-share:server=130.207.66.142,share=raw_data/Confocal/Carolyn/2020/Chronic wounds/images metadata.csv', header = TRUE)

for(row in 1:length(metaData.df[[1]])){
  metaData.df$Condition[[row]] = str_split(metaData.df$SampleCode[[row]],"_")[[1]][[1]]
}
metaData.df<-metaData.df %>% filter(!is.na(mouse))#removes the last row

metaData.df<- metaData.df %>% #remove samples that have already ran
  filter(!SampleCode == "pqsL_d4_16") %>%
  filter(!SampleCode == "mono_d1_03") %>%#stalled
  filter(!SampleCode == "mono_d1_02") %>% #ran
  filter(!SampleCode == "mono_d1_01") %>% #ran
  filter(!SampleCode == "mono_d1_04") %>% #ran
  filter(!SampleCode == "mono_d1_05") %>% #ran
  filter(!SampleCode == "mono_d1_06") %>%  #seemed to have stalled but data file is saved
  filter(!SampleCode == "mono_d1_07") %>% #seemed to have stalled but data file is saved
  filter(!SampleCode == "mono_d1_08") %>%
  filter(!SampleCode == "mono_d1_09") %>%
  filter(!SampleCode == "mono_d1_10") %>%
  filter(!SampleCode == "mono_d1_11") %>%
  filter(!SampleCode == "mono_d1_12") %>%
  filter(!SampleCode == "mono_d1_13") %>%
  filter(!SampleCode == "mono_d1_14") %>%
  filter(!SampleCode == "mono_d1_15") %>%
  filter(!SampleCode == "mono_d4_01") %>%
  filter(!SampleCode == "mono_d4_02") %>%
  filter(!SampleCode == "mono_d4_03") %>%
  filter(!SampleCode == "mono_d4_04") 

metaData.df<-metaData.df %>% filter(!Condition == "mono") %>% 
  filter(!Condition == "pawt") %>% 
  filter(!Condition == "paphz") %>% 
  filter(!Condition == "papqsL")
  
  tic()
  parentFolder<- '/run/user/937561/gvfs/smb-share:server=130.207.66.142,share=raw_data/Confocal/Carolyn/2020/Chronic wounds/Binary Images/'
  #parentFolder<- '/Volumes/raw_data/Confocal/Carolyn/2020/Chronic wounds/Binary Images/'
  sampleFolder<-paste0(parentFolder, sampleName)
  attrList<-str_split(sampleName,"_")[[1]]
  print(sampleName)
  fileList<-list.files(path = sampleFolder, full.names = TRUE)
  print(paste("# of files:", length(fileList)))
  if(length(fileList)<1){
    print("empty set")
  }else{
  greenImg<-fileList[grep("G_",fileList)]
  redImg<-fileList[grep("R_",fileList)]
  propOcData<-AllDataPipeline(Slices2threeD(redImg),Slices2threeD(greenImg), 
                                     xydimSearch=round(30/xyDim),zdimSearch =round(30/zDim),
                                     sampleSize=1000,xyRealDim=xyDim,
                                     zRealDim = zDim, pipeBinSize = 1)
  propOcData$Condition <- attrList[1]
  propOcData$TimePoint <- attrList[2]
  propOcData$Replicate <- attrList[3]
  write.csv(propOcData, paste0("/run/user/937561/gvfs/smb-share:server=130.207.66.142,share=raw_data/Confocal/Carolyn/2020/Chronic wounds/PropOc Data/",sampleName,".csv"))
  toc()}
  }

testGetPropOcData<-GetPropOcData("phz_d4_08", .415,.52)
testGetPropOcDataemptyFolder<-GetPropOcData("wt_d1_01", .415,.52)

blah<-pmap(list(metaData.df$SampleCode,metaData.df$xyDim, metaData.df$Zdim),
               GetPropOcData)
boundPmapTest<-bind_rows(testPmap)

#Dummy function
GetDummyOcData<-function(sampleName, xyDim,zDim){
  parentFolder<- '/Volumes/raw_data/Confocal/Carolyn/2020/Chronic wounds/Binary Images/'
  sampleFolder<-paste0(parentFolder, sampleName)
  attrList<-str_split(sampleName,"_")[[1]]
  print(sampleName)
  fileList<-list.files(path = sampleFolder, full.names = TRUE)
  print(paste("# of files:", length(fileList)))
  if(length(fileList)<1){
    print("empty set")
    return(data.frame())
  }else{
  greenImg<-fileList[grep("G_",fileList)]
  redImg<-fileList[grep("R_",fileList)]
  return(as.data.frame(list(length(greenImg), length(redImg))))
  }
  }
testDummyData<-GetDummyOcData("mono_d1_02", .415,.52)
testDummyEmptyFolder<-GetDummyOcData("wt_d1_01", .415,.52)
dummyBind<-bind_rows(list(testDummyData,testDummyEmptyFolder))


testGrep<-list.files(path = '/run/user/937561/gvfs/smb-share:server=130.207.66.142,share=raw_data/Confocal/Carolyn/2020/Chronic wounds/Binary Images/mono_d1_02', full.names = TRUE)
testGrepG<-testGrep[grep("G_",testGrep)]

Slices2threeD<-function(fileList){
  image1<-as.array(readImage(fileList[1], convert = TRUE))#read first image to get its dimensions
  image3D <- array(0, c(dim(image1)[1], dim(image1)[2], length(fileList)))#preallocate array for image given using image dimensions
  for(i in 1:length(fileList)){#keep in mind that it is not zero-index
    #print(paste("loading ch1...", i, "/", length(filesList), filesList[i]))
    image3D[,,i]<-as.array(readImage(fileList[i], convert = TRUE))
  }
  return(image3D)
}

```

```{r running functions}
wt1.1000<-GetPropOcData("3-13-19", 6, 2)
write.csv(wt1.1000, "~/Desktop/Seagate Backup Plus Drive/Good images/PropOcDataAll/wt1-1000-3.csv")

wt2.1000<-GetPropOcData("3-19-19", 6, 2)
write.csv(wt2.1000, "~/Desktop/Seagate Backup Plus Drive/Good images/PropOcDataAll/wt2-1000-3.csv")

wt3.1000<-GetPropOcData("4-17-19", 6, 2)
write.csv(wt3.1000, "~/Desktop/Seagate Backup Plus Drive/Good images/PropOcDataAll/wt3-1000-3.csv")

mut1.1000<-GetPropOcData("4-24-19", 6, 2)
write.csv(mut1.1000, "~/Desktop/Seagate Backup Plus Drive/Good images/PropOcDataAll/mut1-1000-3.csv")

mut2.1000<-GetPropOcData("4-25-19", 6, 2)
write.csv(mut2.1000, "~/Desktop/Seagate Backup Plus Drive/Good images/PropOcDataAll/mut2-1000-3.csv")
mut3.1000<-GetPropOcData("5-8-19", 6, 2)
write.csv(mut3.1000, "~/Desktop/Seagate Backup Plus Drive/Good images/PropOcDataAll/mut3-1000-3.csv")

```
